// Package site provides static site generation for PRISM dashboards.
//
// # Standard PRISM Directory Structure
//
// The recommended way to organize PRISM data is using the standard directory structure:
//
//	{stack-name}/
//	├── stack.json           # Capability stack definition (required)
//	├── model.json           # Maturity model - SLIs, levels, criteria (optional)
//	├── state.json           # Current state - SLI values per time window (optional)
//	└── roadmap.json         # OKRs, initiatives, roadmap items (optional)
//
// This structure keeps all related files together and enables automatic discovery.
// The directory name becomes the URL-safe identifier (converted to kebab-case).
//
// # File Descriptions
//
//   - stack.json: Defines capabilities, layers, categories, and their relationships.
//     See github.com/grokify/prism-capability for the schema.
//
//   - model.json: Defines maturity levels, SLIs, and criteria for measuring capability maturity.
//     See github.com/grokify/prism-maturity/maturity for the schema.
//
//   - state.json: Contains current SLI values organized by time windows (7d, 30d, 90d).
//     See github.com/grokify/prism-maturity for the PRISMDocument schema.
//
//   - roadmap.json: Defines OKRs, initiatives, and roadmap items.
//     See github.com/grokify/prism-roadmap for the schema.
package site

import (
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	capstack "github.com/grokify/prism-capability"
	prism "github.com/grokify/prism-maturity"
	"github.com/grokify/prism-maturity/dashboard"
	"github.com/grokify/prism-maturity/maturity"
)

// Config holds configuration for site generation.
type Config struct {
	// Title is the site title shown on the homepage.
	Title string

	// Description is shown on the homepage.
	Description string

	// StackPaths is a list of capability stack files or directories.
	// Files are loaded directly; directories are scanned for .json files.
	StackPaths []string

	// ModelsDir is the directory containing maturity model JSON files.
	// Model files are looked up as {basename}-model.json or {basename}/model.json
	ModelsDir string

	// StatesDir is the directory containing state JSON files.
	// State files are looked up as {basename}-state.json or {basename}/state.json
	StatesDir string

	// OutputDir is where the generated site will be written.
	OutputDir string

	// Theme is "light" or "dark".
	Theme string

	// BaseURL is the base URL for the site (for links).
	BaseURL string

	// SiteNavJS is the path to the site-nav JavaScript bundle.
	// If empty, uses CDN or embedded version.
	SiteNavJS string

	// HideGeneratedBy hides the "Generated by PRISM" footer message.
	HideGeneratedBy bool

	// CapStackPath is the path to a capability stack for layer-based maturity views.
	CapStackPath string

	// AggregationMethod is the method for aggregating SLI levels: "min" or "avg".
	AggregationMethod string
}

// Generator creates static sites from PRISM data.
type Generator struct {
	config Config
	stacks []*StackData
}

// StackData holds a capability stack with its associated maturity data.
type StackData struct {
	Stack    *capstack.CapabilityStack
	Model    *maturity.Spec
	State    *prism.PRISMDocument
	FileName string
	BaseName string
	Maturity *dashboard.MaturityAggregator
}

// NewGenerator creates a new site generator.
func NewGenerator(config Config) *Generator {
	return &Generator{
		config: config,
	}
}

// Generate creates the static site.
func (g *Generator) Generate() error {
	// Warn if no site-nav JS provided
	if g.config.SiteNavJS == "" {
		fmt.Fprintf(os.Stderr, "Warning: No --site-nav-js provided. Web components (wt-nav, wt-header, etc.) will not work.\n")
		fmt.Fprintf(os.Stderr, "         Build site-nav first: cd web-tools/packages/site-nav && pnpm build\n")
		fmt.Fprintf(os.Stderr, "         Then pass: --site-nav-js=path/to/dist/site-nav.es.js\n\n")
	}

	// Load all stacks
	if err := g.loadStacks(); err != nil {
		return fmt.Errorf("loading stacks: %w", err)
	}

	// Create output directory
	if err := os.MkdirAll(g.config.OutputDir, 0755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	// Generate pages
	if err := g.generateHomepage(); err != nil {
		return fmt.Errorf("generating homepage: %w", err)
	}

	if err := g.generateStackPages(); err != nil {
		return fmt.Errorf("generating stack pages: %w", err)
	}

	if err := g.generateCapabilityPages(); err != nil {
		return fmt.Errorf("generating capability pages: %w", err)
	}

	// Copy assets
	if err := g.copyAssets(); err != nil {
		return fmt.Errorf("copying assets: %w", err)
	}

	return nil
}

// Standard PRISM directory structure:
//
//	{stack-name}/
//	├── stack.json           # Capability stack definition
//	├── model.json           # Maturity model (SLIs, levels, criteria)
//	├── state.json           # Current state (SLI values)
//	└── roadmap.json         # OKRs, initiatives (optional)
const (
	StandardStackFile   = "stack.json"
	StandardModelFile   = "model.json"
	StandardStateFile   = "state.json"
	StandardRoadmapFile = "roadmap.json"
)

// stackSource represents a capability stack with its source location.
type stackSource struct {
	stackPath string
	modelPath string
	statePath string
	dirName   string // for kebab-case basename
}

func (g *Generator) loadStacks() error {
	// Collect all stack sources from paths
	var sources []stackSource

	for _, path := range g.config.StackPaths {
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("invalid stack path %s: %w", path, err)
		}

		if info.IsDir() {
			// Check if this is a standard PRISM directory (contains stack.json)
			standardStackPath := filepath.Join(path, StandardStackFile)
			if _, err := os.Stat(standardStackPath); err == nil {
				// Standard PRISM directory structure
				src := stackSource{
					stackPath: standardStackPath,
					dirName:   filepath.Base(path),
				}
				// Check for model.json and state.json in same directory
				modelPath := filepath.Join(path, StandardModelFile)
				if _, err := os.Stat(modelPath); err == nil {
					src.modelPath = modelPath
				}
				statePath := filepath.Join(path, StandardStateFile)
				if _, err := os.Stat(statePath); err == nil {
					src.statePath = statePath
				}
				sources = append(sources, src)
			} else {
				// Legacy: scan directory for .json files (not standard structure)
				entries, err := os.ReadDir(path)
				if err != nil {
					return fmt.Errorf("reading directory %s: %w", path, err)
				}
				for _, entry := range entries {
					if entry.IsDir() {
						// Check subdirectory for standard structure
						subPath := filepath.Join(path, entry.Name())
						subStackPath := filepath.Join(subPath, StandardStackFile)
						if _, err := os.Stat(subStackPath); err == nil {
							src := stackSource{
								stackPath: subStackPath,
								dirName:   entry.Name(),
							}
							modelPath := filepath.Join(subPath, StandardModelFile)
							if _, err := os.Stat(modelPath); err == nil {
								src.modelPath = modelPath
							}
							statePath := filepath.Join(subPath, StandardStateFile)
							if _, err := os.Stat(statePath); err == nil {
								src.statePath = statePath
							}
							sources = append(sources, src)
						}
					} else if strings.HasSuffix(entry.Name(), ".json") {
						// Legacy: individual JSON files in directory
						sources = append(sources, stackSource{
							stackPath: filepath.Join(path, entry.Name()),
						})
					}
				}
			}
		} else {
			// Single file
			if strings.HasSuffix(path, ".json") {
				sources = append(sources, stackSource{stackPath: path})
			} else {
				return fmt.Errorf("stack file must be .json: %s", path)
			}
		}
	}

	// Load each stack source
	for _, src := range sources {
		stack, err := capstack.LoadFromFile(src.stackPath)
		if err != nil {
			return fmt.Errorf("loading stack %s: %w", src.stackPath, err)
		}

		// Determine base name for URLs
		var rawBaseName string
		if src.dirName != "" {
			// Standard structure: use directory name
			rawBaseName = src.dirName
		} else {
			// Legacy: use filename without extension
			rawBaseName = strings.TrimSuffix(filepath.Base(src.stackPath), ".json")
		}
		baseName := toKebabCase(rawBaseName)

		sd := &StackData{
			Stack:    stack,
			FileName: filepath.Base(src.stackPath),
			BaseName: baseName,
		}

		// Load model - prefer co-located file from standard structure
		if src.modelPath != "" {
			if model, err := maturity.ReadSpecFile(src.modelPath); err == nil {
				sd.Model = model
			}
		}
		// Fallback to models directory lookup
		if sd.Model == nil {
			g.loadModelForStack(sd, rawBaseName)
			if sd.Model == nil && baseName != rawBaseName {
				g.loadModelForStack(sd, baseName)
			}
		}

		// Load state - prefer co-located file from standard structure
		if src.statePath != "" {
			if stateData, err := os.ReadFile(src.statePath); err == nil {
				var stateDoc prism.PRISMDocument
				if json.Unmarshal(stateData, &stateDoc) == nil {
					sd.State = &stateDoc
				}
			}
		}
		// Fallback to states directory lookup
		if sd.State == nil {
			g.loadStateForStack(sd, rawBaseName)
			if sd.State == nil && baseName != rawBaseName {
				g.loadStateForStack(sd, baseName)
			}
		}

		// Create maturity aggregator if we have all the data
		if sd.Model != nil && sd.State != nil {
			var aggMethod dashboard.AggregationMethod
			switch g.config.AggregationMethod {
			case "avg":
				aggMethod = dashboard.AggregationAvg
			default:
				aggMethod = dashboard.AggregationMin
			}
			sd.Maturity = dashboard.NewMaturityAggregator(sd.Model, sd.Stack, sd.State, aggMethod)
		}

		g.stacks = append(g.stacks, sd)
	}

	return nil
}

func (g *Generator) loadModelForStack(sd *StackData, baseName string) {
	if g.config.ModelsDir == "" {
		return
	}

	// Try {baseName}-model.json
	modelPath := filepath.Join(g.config.ModelsDir, baseName+"-model.json")
	if _, err := os.Stat(modelPath); err == nil {
		if model, err := maturity.ReadSpecFile(modelPath); err == nil {
			sd.Model = model
			return
		}
	}

	// Try {baseName}/model.json
	modelPath = filepath.Join(g.config.ModelsDir, baseName, "model.json")
	if _, err := os.Stat(modelPath); err == nil {
		if model, err := maturity.ReadSpecFile(modelPath); err == nil {
			sd.Model = model
		}
	}
}

func (g *Generator) loadStateForStack(sd *StackData, baseName string) {
	if g.config.StatesDir == "" {
		return
	}

	// Try {baseName}-state.json
	statePath := filepath.Join(g.config.StatesDir, baseName+"-state.json")
	if _, err := os.Stat(statePath); err == nil {
		if stateData, err := os.ReadFile(statePath); err == nil {
			var stateDoc prism.PRISMDocument
			if json.Unmarshal(stateData, &stateDoc) == nil {
				sd.State = &stateDoc
				return
			}
		}
	}

	// Try {baseName}/state.json
	statePath = filepath.Join(g.config.StatesDir, baseName, "state.json")
	if _, err := os.Stat(statePath); err == nil {
		if stateData, err := os.ReadFile(statePath); err == nil {
			var stateDoc prism.PRISMDocument
			if json.Unmarshal(stateData, &stateDoc) == nil {
				sd.State = &stateDoc
			}
		}
	}
}

func (g *Generator) generateHomepage() error {
	tmpl, err := template.New("homepage").Parse(homepageTemplate)
	if err != nil {
		return err
	}

	data := struct {
		Title           string
		Description     string
		Theme           string
		Stacks          []*StackData
		BaseURL         string
		HasSiteNavJS    bool
		HideGeneratedBy bool
	}{
		Title:           g.config.Title,
		Description:     g.config.Description,
		Theme:           g.config.Theme,
		Stacks:          g.stacks,
		BaseURL:         g.config.BaseURL,
		HasSiteNavJS:    g.config.SiteNavJS != "",
		HideGeneratedBy: g.config.HideGeneratedBy,
	}

	outPath := filepath.Join(g.config.OutputDir, "index.html")
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, data)
}

// StackPageData holds data for stack page templates.
type StackPageData struct {
	Title               string
	PageTitle           string
	Theme               string
	Stack               *capstack.CapabilityStack
	StackData           *StackData
	CapMaturity         map[string]float64
	CapSLICount         map[string]int // Number of SLIs per capability
	CapsByLayer         []CapabilityGroup
	CapsByCategory      []CapabilityGroup
	MetricsByLayer      []SLIGroup
	MetricsByCat        []SLIGroup
	ThresholdMatrix     []ThresholdMatrixRow
	ThresholdMatrixJSON template.JS
	SiteTitle           string
	BaseURL             string
	AllStacks           []*StackData
	HasSiteNavJS        bool
	HasModel            bool
	CurrentPage         string // "caps-by-layer", "caps-by-category", "metrics", "metrics-by-layer", "metrics-by-category"
	HideGeneratedBy     bool
}

// ThresholdMatrixRow represents a row in the threshold matrix table.
type ThresholdMatrixRow struct {
	Category     string  `json:"category"`
	Name         string  `json:"name"`
	Unit         string  `json:"unit"`
	Tags         string  `json:"tags"`
	Frameworks   string  `json:"frameworks"`
	CurrentLevel float64 `json:"currentLevel"` // Current maturity level (e.g., 2.5)
	CurrentValue string  `json:"currentValue"` // Current metric value with unit
	TargetQ1     float64 `json:"targetQ1"`     // Target level for Q+1
	TargetQ2     float64 `json:"targetQ2"`     // Target level for Q+2
	M1           string  `json:"m1"`
	M2           string  `json:"m2"`
	M3           string  `json:"m3"`
	M4           string  `json:"m4"`
	M5           string  `json:"m5"`
}

func (g *Generator) generateStackPages() error {
	if err := os.MkdirAll(filepath.Join(g.config.OutputDir, "stacks"), 0755); err != nil {
		return err
	}

	funcMap := template.FuncMap{
		"json": func(v interface{}) template.JS {
			b, _ := json.Marshal(v)
			return template.JS(b) //nolint:gosec // G203: Safe - JSON data for templates
		},
		"statusVariant": statusVariant,
		"kebab":         toKebabCase,
		"maturityLevel": func(capID string, capMaturity map[string]float64) float64 {
			if level, ok := capMaturity[capID]; ok {
				return level
			}
			return 0
		},
		"sliCount": func(capID string, capSLICount map[string]int) int {
			if count, ok := capSLICount[capID]; ok {
				return count
			}
			return 0
		},
	}

	// Parse all templates
	capsByLayerTmpl, err := template.New("caps-by-layer").Funcs(funcMap).Parse(capsByLayerTemplate)
	if err != nil {
		return fmt.Errorf("parsing caps-by-layer template: %w", err)
	}
	capsByCategoryTmpl, err := template.New("caps-by-category").Funcs(funcMap).Parse(capsByCategoryTemplate)
	if err != nil {
		return fmt.Errorf("parsing caps-by-category template: %w", err)
	}
	metricsByLayerTmpl, err := template.New("metrics-by-layer").Funcs(funcMap).Parse(metricsByLayerTemplate)
	if err != nil {
		return fmt.Errorf("parsing metrics-by-layer template: %w", err)
	}
	metricsByCategoryTmpl, err := template.New("metrics-by-category").Funcs(funcMap).Parse(metricsByCategoryTemplate)
	if err != nil {
		return fmt.Errorf("parsing metrics-by-category template: %w", err)
	}
	metricsTableTmpl, err := template.New("metrics-table").Funcs(funcMap).Parse(metricsTableTemplate)
	if err != nil {
		return fmt.Errorf("parsing metrics-table template: %w", err)
	}

	for _, sd := range g.stacks {
		// Build capability maturity and SLI count maps
		capMaturity := make(map[string]float64)
		capSLICount := make(map[string]int)
		if sd.Maturity != nil {
			for _, cm := range sd.Maturity.GetCapabilityMaturities() {
				capMaturity[cm.CapabilityID] = cm.AggregateLevel
				capSLICount[cm.CapabilityID] = len(cm.SLIIDs)
			}
		}

		// Build grouped data
		capsByLayer := g.buildCapabilitiesByLayer(sd)
		capsByCategory := g.buildCapabilitiesByCategory(sd)
		metricsByLayer := g.buildSLIsByLayer(sd)
		metricsByCat := g.buildSLIsByCategory(sd)
		thresholdMatrix := g.buildThresholdMatrix(sd)

		// Convert threshold matrix to JSON for template
		var thresholdMatrixJSON template.JS
		if jsonData, err := json.Marshal(thresholdMatrix); err == nil {
			thresholdMatrixJSON = template.JS(jsonData) //nolint:gosec // G203: Safe - JSON data for templates
		} else {
			thresholdMatrixJSON = "[]"
		}

		baseData := StackPageData{
			Title:               sd.Stack.Metadata.Title,
			Theme:               g.config.Theme,
			Stack:               sd.Stack,
			StackData:           sd,
			CapMaturity:         capMaturity,
			CapSLICount:         capSLICount,
			CapsByLayer:         capsByLayer,
			CapsByCategory:      capsByCategory,
			MetricsByLayer:      metricsByLayer,
			MetricsByCat:        metricsByCat,
			ThresholdMatrix:     thresholdMatrix,
			ThresholdMatrixJSON: thresholdMatrixJSON,
			SiteTitle:           g.config.Title,
			BaseURL:             g.config.BaseURL,
			AllStacks:           g.stacks,
			HasSiteNavJS:        g.config.SiteNavJS != "",
			HasModel:            sd.Model != nil,
			HideGeneratedBy:     g.config.HideGeneratedBy,
		}

		// Generate 5 pages per stack (alphabetically ordered)
		pages := []struct {
			filename    string
			pageTitle   string
			currentPage string
			tmpl        *template.Template
		}{
			{"capabilities-by-category-" + sd.BaseName + ".html", "Capabilities by Category", "caps-by-category", capsByCategoryTmpl},
			{"capabilities-by-layer-" + sd.BaseName + ".html", "Capabilities by Layer", "caps-by-layer", capsByLayerTmpl},
			{"metrics-" + sd.BaseName + ".html", "Metrics", "metrics", metricsTableTmpl},
			{"metrics-by-category-" + sd.BaseName + ".html", "Metrics by Category", "metrics-by-category", metricsByCategoryTmpl},
			{"metrics-by-layer-" + sd.BaseName + ".html", "Metrics by Layer", "metrics-by-layer", metricsByLayerTmpl},
		}

		for _, page := range pages {
			data := baseData
			data.PageTitle = page.pageTitle
			data.CurrentPage = page.currentPage

			outPath := filepath.Join(g.config.OutputDir, "stacks", page.filename)
			f, err := os.Create(outPath)
			if err != nil {
				return err
			}

			if err := page.tmpl.Execute(f, data); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}
	}

	return nil
}

// buildCapabilitiesByLayer groups capabilities by their LayerID field.
func (g *Generator) buildCapabilitiesByLayer(sd *StackData) []CapabilityGroup {
	layerMap := make(map[string][]capstack.Capability)
	layerOrder := make(map[string]int)
	layerNames := make(map[string]string)

	// Get layer order and names from stack
	for i, layer := range sd.Stack.Layers {
		layerOrder[layer.ID] = i
		layerNames[layer.ID] = layer.Name
	}

	// Group capabilities by their LayerID
	for _, cap := range sd.Stack.AllCapabilities() {
		layerID := cap.LayerID
		if layerID == "" {
			layerID = "other"
		}
		layerMap[layerID] = append(layerMap[layerID], cap)
		if _, ok := layerOrder[layerID]; !ok {
			layerOrder[layerID] = 100
			layerNames[layerID] = layerID
		}
	}

	// Build sorted groups
	var groups []CapabilityGroup
	for layerID, caps := range layerMap {
		groups = append(groups, CapabilityGroup{
			ID:           layerID,
			Name:         layerNames[layerID],
			Order:        layerOrder[layerID],
			Capabilities: caps,
		})
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].Order < groups[j].Order
	})

	return groups
}

func (g *Generator) generateCapabilityPages() error {
	if err := os.MkdirAll(filepath.Join(g.config.OutputDir, "capabilities"), 0755); err != nil {
		return err
	}

	tmpl, err := template.New("capability").Funcs(template.FuncMap{
		"json": func(v interface{}) template.JS {
			b, _ := json.Marshal(v)
			return template.JS(b) //nolint:gosec // G203: Safe - JSON data for templates
		},
		"kebab": toKebabCase,
	}).Parse(capabilityPageTemplate)
	if err != nil {
		return err
	}

	for _, sd := range g.stacks {
		for _, cap := range sd.Stack.AllCapabilities() {
			// Get maturity info if available
			var maturityLevel float64
			var sliCount int
			var sliBullets []SLIBulletData

			if sd.Maturity != nil {
				for _, cm := range sd.Maturity.GetCapabilityMaturities() {
					if cm.CapabilityID == cap.ID {
						maturityLevel = cm.AggregateLevel
						sliCount = len(cm.SLIIDs)
						// Build bullet data for each SLI
						sliBullets = g.buildSLIBullets(sd, cm.SLIIDs, cm.SLILevels)
						break
					}
				}
			}

			data := struct {
				Title           string
				Theme           string
				Capability      capstack.Capability
				Stack           *capstack.CapabilityStack
				StackData       *StackData
				MaturityLevel   float64
				SLICount        int
				SLIBullets      []SLIBulletData
				SiteTitle       string
				BaseURL         string
				HasSiteNavJS    bool
				AllStacks       []*StackData
				HideGeneratedBy bool
			}{
				Title:           cap.Name,
				Theme:           g.config.Theme,
				Capability:      cap,
				Stack:           sd.Stack,
				StackData:       sd,
				MaturityLevel:   maturityLevel,
				SLICount:        sliCount,
				SLIBullets:      sliBullets,
				SiteTitle:       g.config.Title,
				BaseURL:         g.config.BaseURL,
				HasSiteNavJS:    g.config.SiteNavJS != "",
				AllStacks:       g.stacks,
				HideGeneratedBy: g.config.HideGeneratedBy,
			}

			// Use stack-capability as filename to avoid conflicts
			capID := toKebabCase(cap.ID)
			outPath := filepath.Join(g.config.OutputDir, "capabilities", sd.BaseName+"-"+capID+".html")
			f, err := os.Create(outPath)
			if err != nil {
				return err
			}

			if err := tmpl.Execute(f, data); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}
	}

	return nil
}

func (g *Generator) copyAssets() error {
	assetsDir := filepath.Join(g.config.OutputDir, "assets")
	if err := os.MkdirAll(assetsDir, 0755); err != nil {
		return err
	}

	// Write embedded CSS
	cssPath := filepath.Join(assetsDir, "site.css")
	if err := os.WriteFile(cssPath, []byte(siteCSS), 0644); err != nil { //nolint:gosec // G306: Web assets need 0644 for server access
		return err
	}

	// If custom site-nav JS provided, copy it
	if g.config.SiteNavJS != "" {
		jsData, err := os.ReadFile(g.config.SiteNavJS)
		if err != nil {
			return fmt.Errorf("reading site-nav JS: %w", err)
		}
		jsPath := filepath.Join(assetsDir, "site-nav.es.js")
		if err := os.WriteFile(jsPath, jsData, 0644); err != nil { //nolint:gosec // G306: Web assets need 0644 for server access
			return err
		}
	}

	return nil
}

// buildSLIBullets creates bullet chart data for a list of SLIs.
func (g *Generator) buildSLIBullets(sd *StackData, sliIDs []string, sliLevels []float64) []SLIBulletData {
	var bullets []SLIBulletData

	if sd.Model == nil {
		return bullets
	}

	for i, sliID := range sliIDs {
		// Get SLI definition
		sli := sd.Model.GetSLI(sliID)
		if sli == nil {
			continue
		}

		// Get current level
		currentLevel := 1.0
		if i < len(sliLevels) {
			currentLevel = sliLevels[i]
		}

		// Get current value from state
		var currentValue float64
		if sd.State != nil && sd.State.SLIState != nil {
			if state, ok := sd.State.SLIState[sliID]; ok && state != nil && state.Windows != nil {
				// Try 30d window first
				if ws, ok := state.Windows["30d"]; ok && ws != nil {
					currentValue = ws.Value
				} else {
					for _, ws := range state.Windows {
						if ws != nil {
							currentValue = ws.Value
							break
						}
					}
				}
			}
		}

		// Build thresholds from criteria
		thresholds := g.buildSLIThresholds(sd.Model, sliID)

		bullet := SLIBulletData{
			ID:           sliID,
			Title:        sli.Name,
			Subtitle:     sli.MetricName,
			Measures:     []float64{currentLevel},
			Markers:      []float64{},        // Target could be added if available
			Ranges:       []float64{3, 4, 5}, // M1-M3, M4, M5 zones
			Thresholds:   thresholds,
			CurrentValue: currentValue,
			Unit:         sli.Unit,
		}

		bullets = append(bullets, bullet)
	}

	return bullets
}

// buildSLIThresholds extracts M1-M5 threshold values for an SLI.
func (g *Generator) buildSLIThresholds(spec *maturity.Spec, sliID string) []SLIThreshold {
	var thresholds []SLIThreshold

	for _, domain := range spec.Domains {
		for _, level := range domain.Levels {
			for _, criterion := range level.Criteria {
				if criterion.SLIID != sliID {
					continue
				}

				// Format value string
				var valueStr string
				if criterion.IsQualitative() {
					valueStr = "Tracked"
				} else {
					unit := criterion.GetUnit(spec)
					if unit != "" {
						valueStr = fmt.Sprintf("%.0f%s", criterion.Target, unit)
					} else {
						valueStr = fmt.Sprintf("%.0f", criterion.Target)
					}
				}

				thresholds = append(thresholds, SLIThreshold{
					Level:    level.Level,
					Value:    criterion.Target,
					ValueStr: valueStr,
					Operator: criterion.Operator,
				})
			}
		}
	}

	return thresholds
}

// buildCapabilitiesByCategory groups capabilities by their CategoryID field.
// This mirrors how buildCapabilitiesByLayer works, using the stack's Categories
// for ordering and naming instead of deriving category from SLIs.
func (g *Generator) buildCapabilitiesByCategory(sd *StackData) []CapabilityGroup {
	categoryMap := make(map[string][]capstack.Capability)
	categoryOrder := make(map[string]int)
	categoryNames := make(map[string]string)

	// Get category order and names from stack
	for i, cat := range sd.Stack.Categories {
		categoryOrder[cat.ID] = i
		categoryNames[cat.ID] = cat.Name
	}

	// Group capabilities by their CategoryID
	for _, cap := range sd.Stack.AllCapabilities() {
		categoryID := cap.CategoryID
		if categoryID == "" {
			categoryID = "uncategorized"
		}
		categoryMap[categoryID] = append(categoryMap[categoryID], cap)
		if _, ok := categoryOrder[categoryID]; !ok {
			categoryOrder[categoryID] = 100 // default order for unknown categories
			// Capitalize first letter for unknown categories
			name := categoryID
			if len(name) > 0 {
				name = strings.ToUpper(name[:1]) + name[1:]
			}
			categoryNames[categoryID] = name
		}
	}

	// Build sorted groups
	var groups []CapabilityGroup
	for catID, caps := range categoryMap {
		name := categoryNames[catID]
		if name == "" {
			name = catID
		}
		groups = append(groups, CapabilityGroup{
			ID:           catID,
			Name:         name,
			Order:        categoryOrder[catID],
			Capabilities: caps,
		})
	}

	// Sort by order
	sort.Slice(groups, func(i, j int) bool {
		return groups[i].Order < groups[j].Order
	})

	return groups
}

// buildSLIsByLayer groups all SLIs with bullet data by layer.
func (g *Generator) buildSLIsByLayer(sd *StackData) []SLIGroup {
	if sd.Model == nil {
		return nil
	}

	layerMap := make(map[string][]SLIBulletData)
	layerOrder := make(map[string]int)
	layerNames := make(map[string]string)

	// Get layer order from stack
	for i, layer := range sd.Stack.Layers {
		layerOrder[layer.ID] = i
		layerNames[layer.ID] = layer.Name
	}

	// Build SLI bullets for all SLIs, grouped by layer
	for _, sli := range sd.Model.AllSLIs() {
		layerID := sli.Layer
		if layerID == "" {
			layerID = "other"
		}

		// Get current level for this SLI
		var currentLevel float64 = 1.0
		if sd.Maturity != nil {
			// Find SLI level
			currentLevel = g.getSLICurrentLevel(sd, sli.ID)
		}

		// Get current value
		var currentValue float64
		if sd.State != nil && sd.State.SLIState != nil {
			if state, ok := sd.State.SLIState[sli.ID]; ok && state != nil && state.Windows != nil {
				if ws, ok := state.Windows["30d"]; ok && ws != nil {
					currentValue = ws.Value
				}
			}
		}

		bullet := SLIBulletData{
			ID:           sli.ID,
			Title:        sli.Name,
			Subtitle:     sli.MetricName,
			Measures:     []float64{currentLevel},
			Markers:      []float64{},
			Ranges:       []float64{3, 4, 5},
			Thresholds:   g.buildSLIThresholds(sd.Model, sli.ID),
			CurrentValue: currentValue,
			Unit:         sli.Unit,
		}

		layerMap[layerID] = append(layerMap[layerID], bullet)
		if _, ok := layerOrder[layerID]; !ok {
			layerOrder[layerID] = 100
			layerNames[layerID] = strings.ToUpper(layerID[:1]) + layerID[1:]
		}
	}

	// Build sorted groups
	var groups []SLIGroup
	for layerID, slis := range layerMap {
		groups = append(groups, SLIGroup{
			ID:    layerID,
			Name:  layerNames[layerID],
			Order: layerOrder[layerID],
			SLIs:  slis,
		})
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].Order < groups[j].Order
	})

	return groups
}

// buildSLIsByCategory groups all SLIs with bullet data by category.
func (g *Generator) buildSLIsByCategory(sd *StackData) []SLIGroup {
	if sd.Model == nil {
		return nil
	}

	categoryMap := make(map[string][]SLIBulletData)
	categoryOrder := make(map[string]int)

	// Get category order from model
	for i, cat := range sd.Model.GetCategoryOrder() {
		categoryOrder[cat] = i
	}

	// Build SLI bullets for all SLIs, grouped by category
	for _, sli := range sd.Model.AllSLIs() {
		category := sli.Category
		if category == "" {
			category = "other"
		}

		// Get current level for this SLI
		var currentLevel float64 = 1.0
		if sd.Maturity != nil {
			currentLevel = g.getSLICurrentLevel(sd, sli.ID)
		}

		// Get current value
		var currentValue float64
		if sd.State != nil && sd.State.SLIState != nil {
			if state, ok := sd.State.SLIState[sli.ID]; ok && state != nil && state.Windows != nil {
				if ws, ok := state.Windows["30d"]; ok && ws != nil {
					currentValue = ws.Value
				}
			}
		}

		bullet := SLIBulletData{
			ID:           sli.ID,
			Title:        sli.Name,
			Subtitle:     sli.MetricName,
			Measures:     []float64{currentLevel},
			Markers:      []float64{},
			Ranges:       []float64{3, 4, 5},
			Thresholds:   g.buildSLIThresholds(sd.Model, sli.ID),
			CurrentValue: currentValue,
			Unit:         sli.Unit,
		}

		categoryMap[category] = append(categoryMap[category], bullet)
		if _, ok := categoryOrder[category]; !ok {
			categoryOrder[category] = 100
		}
	}

	// Build sorted groups
	var groups []SLIGroup
	for catID, slis := range categoryMap {
		name := catID
		if len(name) > 0 {
			name = strings.ToUpper(name[:1]) + name[1:]
		}
		groups = append(groups, SLIGroup{
			ID:    catID,
			Name:  name,
			Order: categoryOrder[catID],
			SLIs:  slis,
		})
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].Order < groups[j].Order
	})

	return groups
}

// getSLICurrentLevel calculates the current maturity level for an SLI.
func (g *Generator) getSLICurrentLevel(sd *StackData, sliID string) float64 {
	if sd.State == nil || sd.Model == nil {
		return 1.0
	}

	// Get SLI value from state
	var sliValue float64
	var hasValue bool

	if sd.State.SLIState != nil {
		if state, ok := sd.State.SLIState[sliID]; ok && state != nil && state.Windows != nil {
			if ws, ok := state.Windows["30d"]; ok && ws != nil {
				sliValue = ws.Value
				hasValue = true
			} else {
				for _, ws := range state.Windows {
					if ws != nil {
						sliValue = ws.Value
						hasValue = true
						break
					}
				}
			}
		}
	}

	if !hasValue {
		return 1.0
	}

	// Calculate level based on criteria
	highestLevel := 1.0
	for _, domain := range sd.Model.Domains {
		for _, level := range domain.Levels {
			for _, criterion := range level.Criteria {
				if criterion.SLIID != sliID {
					continue
				}
				if criterion.CheckMet(sliValue) {
					levelNum := float64(level.Level)
					if levelNum > highestLevel {
						highestLevel = levelNum
					}
				}
			}
		}
	}

	return highestLevel
}

// buildThresholdMatrix creates the threshold matrix data for the metrics table.
// This mirrors the XLSX Threshold Matrix sheet structure.
func (g *Generator) buildThresholdMatrix(sd *StackData) []ThresholdMatrixRow {
	if sd.Model == nil {
		return nil
	}

	// Build a map of SLI ID -> level -> threshold string
	type sliInfo struct {
		id         string
		name       string
		category   string
		unit       string
		tags       []string
		frameworks []string
		thresholds map[int]string
	}

	sliMap := make(map[string]*sliInfo)
	var sliOrder []string

	for _, domain := range sd.Model.Domains {
		for _, level := range domain.Levels {
			for _, criterion := range level.Criteria {
				if criterion.SLIID == "" {
					continue
				}

				info, exists := sliMap[criterion.SLIID]
				if !exists {
					sli := sd.Model.GetSLI(criterion.SLIID)
					name := criterion.SLIID
					category := ""
					unit := ""
					var tags []string
					var frameworks []string

					if sli != nil {
						name = sli.Name
						category = sli.Category
						unit = sli.Unit
						tags = sli.GetNormalizedTags()

						// Collect framework names
						fwSet := make(map[string]bool)
						for _, fm := range sli.FrameworkMappings {
							fwSet[fm.Framework] = true
						}
						for fw := range fwSet {
							frameworks = append(frameworks, fw)
						}
						sort.Strings(frameworks)
					}

					info = &sliInfo{
						id:         criterion.SLIID,
						name:       name,
						category:   category,
						unit:       unit,
						tags:       tags,
						frameworks: frameworks,
						thresholds: make(map[int]string),
					}
					sliMap[criterion.SLIID] = info
					sliOrder = append(sliOrder, criterion.SLIID)
				}

				// Format threshold
				threshold := g.formatCriterionThreshold(criterion, info.unit)
				info.thresholds[level.Level] = threshold
			}
		}
	}

	// Sort by category then name
	sort.Slice(sliOrder, func(i, j int) bool {
		a, b := sliMap[sliOrder[i]], sliMap[sliOrder[j]]
		if a.category != b.category {
			return a.category < b.category
		}
		return a.name < b.name
	})

	// Build result rows
	var rows []ThresholdMatrixRow
	for _, sliID := range sliOrder {
		info := sliMap[sliID]

		// Calculate current maturity level
		currentLevel := g.getSLICurrentLevel(sd, sliID)

		// Get current value from state
		currentValue := ""
		if sd.State != nil && sd.State.SLIState != nil {
			if state, ok := sd.State.SLIState[sliID]; ok && state != nil && state.Windows != nil {
				// Try 30d window first, then any available
				var val float64
				var hasVal bool
				if ws, ok := state.Windows["30d"]; ok && ws != nil {
					val = ws.Value
					hasVal = true
				} else {
					for _, ws := range state.Windows {
						if ws != nil {
							val = ws.Value
							hasVal = true
							break
						}
					}
				}
				if hasVal {
					if info.unit != "" {
						currentValue = fmt.Sprintf("%.2f%s", val, info.unit)
					} else {
						currentValue = fmt.Sprintf("%.2f", val)
					}
				}
			}
		}

		row := ThresholdMatrixRow{
			Category:     info.category,
			Name:         info.name,
			Unit:         info.unit,
			Tags:         strings.Join(info.tags, ", "),
			Frameworks:   strings.Join(info.frameworks, ", "),
			CurrentLevel: currentLevel,
			CurrentValue: currentValue,
			TargetQ1:     0, // Can be populated from roadmap data if available
			TargetQ2:     0, // Can be populated from roadmap data if available
			M1:           info.thresholds[1],
			M2:           info.thresholds[2],
			M3:           info.thresholds[3],
			M4:           info.thresholds[4],
			M5:           info.thresholds[5],
		}
		// Fill empty thresholds with "-"
		if row.M1 == "" {
			row.M1 = "-"
		}
		if row.M2 == "" {
			row.M2 = "-"
		}
		if row.M3 == "" {
			row.M3 = "-"
		}
		if row.M4 == "" {
			row.M4 = "-"
		}
		if row.M5 == "" {
			row.M5 = "-"
		}
		rows = append(rows, row)
	}

	return rows
}

// formatCriterionThreshold formats a criterion's threshold for display.
func (g *Generator) formatCriterionThreshold(c maturity.Criterion, unit string) string {
	if c.Operator == "exists" {
		return "Tracked"
	}

	symbol := maturity.OperatorSymbol(c.Operator)
	if unit != "" {
		return fmt.Sprintf("%s%v%s", symbol, c.Target, unit)
	}
	return fmt.Sprintf("%s%v", symbol, c.Target)
}

// SLIBulletData holds data for rendering an SLI as a bullet chart.
type SLIBulletData struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Subtitle     string         `json:"subtitle"`
	Measures     []float64      `json:"measures"`   // Current maturity level
	Markers      []float64      `json:"markers"`    // Target level (optional)
	Ranges       []float64      `json:"ranges"`     // Always [3, 4, 5] for M1-M3, M4, M5
	Thresholds   []SLIThreshold `json:"thresholds"` // M1-M5 threshold values
	CurrentValue float64        `json:"currentValue"`
	Unit         string         `json:"unit"`
}

// SLIThreshold holds threshold data for a maturity level.
type SLIThreshold struct {
	Level    int     `json:"level"`
	Value    float64 `json:"value"`
	ValueStr string  `json:"valueStr"`
	Operator string  `json:"operator"`
}

// CapabilityGroup holds a group of capabilities (by layer or category).
type CapabilityGroup struct {
	ID           string                `json:"id"`
	Name         string                `json:"name"`
	Order        int                   `json:"order"`
	Capabilities []capstack.Capability `json:"capabilities"`
}

// SLIGroup holds a group of SLIs with bullet chart data.
type SLIGroup struct {
	ID    string          `json:"id"`
	Name  string          `json:"name"`
	Order int             `json:"order"`
	SLIs  []SLIBulletData `json:"slis"`
}

// statusVariant maps a capability status to a badge variant.
func statusVariant(status string) string {
	switch status {
	case "operational":
		return "success"
	case "implemented":
		return "primary"
	case "in-progress":
		return "warning"
	case "planned":
		return "default"
	case "deprecated":
		return "error"
	default:
		return "default"
	}
}

// toKebabCase converts a string to kebab-case.
// Examples:
//   - "My Stack" -> "my-stack"
//   - "Operations_SaaS" -> "operations-saas"
//   - "SecurityCapabilities" -> "security-capabilities"
//   - "already-kebab-case" -> "already-kebab-case"
func toKebabCase(s string) string {
	// First, handle camelCase and PascalCase by inserting hyphens before capitals
	var result strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := rune(s[i-1])
				// Insert hyphen if previous char is lowercase or if we're starting a new word
				if unicode.IsLower(prev) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1]))) {
					result.WriteRune('-')
				}
			}
			result.WriteRune(unicode.ToLower(r))
		} else {
			result.WriteRune(r)
		}
	}

	str := result.String()

	// Replace common separators with hyphens
	str = strings.ReplaceAll(str, "_", "-")
	str = strings.ReplaceAll(str, " ", "-")
	str = strings.ReplaceAll(str, ".", "-")

	// Remove any non-alphanumeric characters except hyphens
	reg := regexp.MustCompile(`[^a-z0-9-]+`)
	str = reg.ReplaceAllString(str, "")

	// Collapse multiple hyphens into one
	reg = regexp.MustCompile(`-+`)
	str = reg.ReplaceAllString(str, "-")

	// Trim leading/trailing hyphens
	str = strings.Trim(str, "-")

	return str
}

// WriteJSON writes JSON data to a writer.
func WriteJSON(w io.Writer, v interface{}) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}
