package sitegen

// homepageTemplate is the HTML template for the homepage.
const homepageTemplate = `<!DOCTYPE html>
<html lang="en" theme="{{.Theme}}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{.Title}}</title>
  <link rel="stylesheet" href="{{.BaseURL}}/assets/site.css">
  {{if .HasSiteNavJS}}<script type="module" src="{{.BaseURL}}/assets/site-nav.es.js"></script>{{end}}
</head>
<body>
  {{if .HasSiteNavJS}}
  <wt-navbar id="navbar" theme="{{.Theme}}"></wt-navbar>
  {{end}}

  <div class="site-container">
    {{if not .HasSiteNavJS}}
    <header class="fallback-header">
      <h1>{{.Title}}</h1>
      {{if .Description}}<p>{{.Description}}</p>{{end}}
    </header>
    {{end}}

    <main class="site-main">
      {{if .Description}}
      <p class="site-description">{{.Description}}</p>
      {{end}}

      <section class="stacks-grid">
        <h2 class="section-title">Capability Stacks</h2>
        <div class="cards-grid">
          {{range .Stacks}}
          <a href="{{$.BaseURL}}/stacks/capabilities-by-category-{{.BaseName}}.html" class="stack-card">
            <div class="stack-card-header">
              <h3 class="stack-card-title">{{.Stack.Metadata.Title}}</h3>
              {{if .Stack.Metadata.Version}}
              <span class="stack-card-version">v{{.Stack.Metadata.Version}}</span>
              {{end}}
            </div>
            {{if .Stack.Metadata.Description}}
            <p class="stack-card-description">{{.Stack.Metadata.Description}}</p>
            {{end}}
            <div class="stack-card-stats">
              <div class="stat">
                <span class="stat-value">{{len .Stack.Layers}}</span>
                <span class="stat-label">Layers</span>
              </div>
              <div class="stat">
                <span class="stat-value">{{len .Stack.Capabilities}}</span>
                <span class="stat-label">Capabilities</span>
              </div>
              {{if .Model}}
              <div class="stat">
                <span class="stat-value">{{len .Model.SLIs}}</span>
                <span class="stat-label">Metrics</span>
              </div>
              {{end}}
            </div>
          </a>
          {{end}}
        </div>
      </section>
    </main>

    {{if not .HideGeneratedBy}}
    <footer class="site-footer">
      <p>Generated by <a href="https://github.com/grokify/prism">PRISM</a></p>
    </footer>
    {{end}}
  </div>

  {{if .HasSiteNavJS}}
  <script type="module">
    const navbar = document.getElementById('navbar');

    // Configure navbar with stacks
    navbar.config = {
      baseUrl: '{{.BaseURL}}',
      brand: {
        name: '{{.Title}}',
        href: '{{.BaseURL}}/',
      },
      dropdowns: [
        {{range .Stacks}}
        {
          id: '{{.BaseName}}',
          label: '{{.Stack.Metadata.Title}}',
          items: [
            { id: 'caps-by-cat', label: 'Capabilities by Category', href: '/stacks/capabilities-by-category-{{.BaseName}}.html' },
            { id: 'caps-by-layer', label: 'Capabilities by Layer', href: '/stacks/capabilities-by-layer-{{.BaseName}}.html' },
            {{if .Model}}
            { id: 'metrics-by-cat', label: 'Metrics by Category', href: '/stacks/metrics-by-category-{{.BaseName}}.html' },
            { id: 'metrics-by-layer', label: 'Metrics by Layer', href: '/stacks/metrics-by-layer-{{.BaseName}}.html' },
            {{end}}
          ],
        },
        {{end}}
      ],
    };

    // Theme toggle handling - sync navbar, badges, and page
    function applyTheme(theme) {
      document.documentElement.setAttribute('theme', theme);
      navbar?.setAttribute('theme', theme);
      document.querySelectorAll('wt-badge').forEach(el => el.setAttribute('theme', theme));
    }

    navbar?.addEventListener('wt-theme-change', (e) => {
      const { resolvedTheme } = e.detail;
      applyTheme(resolvedTheme);
    });
  </script>
  {{end}}
</body>
</html>`

// stackPageHeader is the shared HTML header for stack pages.
const stackPageHeader = `<!DOCTYPE html>
<html lang="en" theme="{{.Theme}}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{.PageTitle}} - {{.Title}} - PRISM</title>
  <link rel="stylesheet" href="{{.BaseURL}}/assets/site.css">
  {{if .HasSiteNavJS}}<script type="module" src="{{.BaseURL}}/assets/site-nav.es.js"></script>{{end}}
</head>
<body>
  {{if .HasSiteNavJS}}
  <wt-navbar id="navbar" theme="{{.Theme}}"></wt-navbar>
  {{end}}
`

// stackPageNav generates the page navigation tabs.
const stackPageNav = `
    {{if not .HasSiteNavJS}}
    <nav class="top-nav">
      <a href="{{.BaseURL}}/" class="top-nav-link">← {{.SiteTitle}}</a>
      <span class="top-nav-sep">›</span>
      <span class="top-nav-current">{{.Title}}</span>
    </nav>
    {{end}}

    <!-- Page Navigation Tabs -->
    <div class="page-nav">
      <a href="{{.BaseURL}}/stacks/capabilities-by-category-{{.StackData.BaseName}}.html" class="page-nav-link{{if eq .CurrentPage "caps-by-category"}} active{{end}}">Capabilities by Category</a>
      <a href="{{.BaseURL}}/stacks/capabilities-by-layer-{{.StackData.BaseName}}.html" class="page-nav-link{{if eq .CurrentPage "caps-by-layer"}} active{{end}}">Capabilities by Layer</a>
      {{if .HasModel}}
      <a href="{{.BaseURL}}/stacks/metrics-{{.StackData.BaseName}}.html" class="page-nav-link{{if eq .CurrentPage "metrics"}} active{{end}}">Metrics</a>
      <a href="{{.BaseURL}}/stacks/metrics-by-category-{{.StackData.BaseName}}.html" class="page-nav-link{{if eq .CurrentPage "metrics-by-category"}} active{{end}}">Metrics by Category</a>
      <a href="{{.BaseURL}}/stacks/metrics-by-layer-{{.StackData.BaseName}}.html" class="page-nav-link{{if eq .CurrentPage "metrics-by-layer"}} active{{end}}">Metrics by Layer</a>
      {{end}}
    </div>
`

// stackFilterSection is the filter controls for stack pages.
const stackFilterSection = `
    <!-- Filters -->
    <div class="filters-section">
      <div class="filter-group">
        <div class="filter-label">Status</div>
        <div class="filter-buttons" id="status-filters">
          <button class="filter-btn active" data-filter="status" data-value="operational">Operational</button>
          <button class="filter-btn active" data-filter="status" data-value="implemented">Implemented</button>
          <button class="filter-btn active" data-filter="status" data-value="in-progress">In Progress</button>
          <button class="filter-btn active" data-filter="status" data-value="planned">Planned</button>
          <button class="filter-btn" data-filter="status" data-value="deprecated">Deprecated</button>
        </div>
      </div>
      {{if .HasModel}}
      <div class="filter-group">
        <div class="filter-label">Maturity Level</div>
        <div class="filter-buttons" id="maturity-filters">
          <button class="filter-btn active" data-filter="maturity" data-value="1">M1</button>
          <button class="filter-btn active" data-filter="maturity" data-value="2">M2</button>
          <button class="filter-btn active" data-filter="maturity" data-value="3">M3</button>
          <button class="filter-btn active" data-filter="maturity" data-value="4">M4</button>
          <button class="filter-btn active" data-filter="maturity" data-value="5">M5</button>
        </div>
      </div>
      {{end}}
    </div>
`

// capabilityFilterScript is the JavaScript for filtering capabilities.
const capabilityFilterScript = `
  <script>
    // Filter logic for capabilities
    function applyCapabilityFilters() {
      const activeStatuses = new Set();
      const activeMaturities = new Set();

      document.querySelectorAll('#status-filters .filter-btn.active').forEach(btn => {
        activeStatuses.add(btn.dataset.value);
      });
      document.querySelectorAll('#maturity-filters .filter-btn.active').forEach(btn => {
        activeMaturities.add(btn.dataset.value);
      });

      document.querySelectorAll('.capability-card').forEach(card => {
        const status = card.dataset.status || '';
        const maturity = card.dataset.maturity || '0';

        const statusMatch = activeStatuses.size === 0 || activeStatuses.has(status);
        const maturityMatch = activeMaturities.size === 0 || maturity === '0' || activeMaturities.has(maturity);

        if (statusMatch && maturityMatch) {
          card.classList.remove('filtered-out');
        } else {
          card.classList.add('filtered-out');
        }
      });
    }

    // Toggle filter buttons
    document.querySelectorAll('.filter-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        btn.classList.toggle('active');
        applyCapabilityFilters();
      });
    });

    // Initial filter application
    applyCapabilityFilters();
  </script>
`

// metricsFilterSection is the filter controls for metrics pages (maturity only).
const metricsFilterSection = `
    <!-- Filters -->
    <div class="filters-section">
      <div class="filter-group">
        <div class="filter-label">Maturity Level</div>
        <div class="filter-buttons" id="maturity-filters">
          <button class="filter-btn active" data-filter="maturity" data-value="1">M1</button>
          <button class="filter-btn active" data-filter="maturity" data-value="2">M2</button>
          <button class="filter-btn active" data-filter="maturity" data-value="3">M3</button>
          <button class="filter-btn active" data-filter="maturity" data-value="4">M4</button>
          <button class="filter-btn active" data-filter="maturity" data-value="5">M5</button>
        </div>
      </div>
    </div>
`

// metricsFilterScript is the JavaScript for filtering metrics.
const metricsFilterScript = `
  <script>
    // Filter logic for metrics - hides filtered rows completely for vertical collapse
    function applyMetricsFilters() {
      const activeMaturities = new Set();

      document.querySelectorAll('#maturity-filters .filter-btn.active').forEach(btn => {
        activeMaturities.add(parseInt(btn.dataset.value));
      });

      let totalVisible = 0;

      // Filter individual metric rows
      document.querySelectorAll('.bullet-row').forEach(row => {
        const levelBadge = row.querySelector('.sli-level-badge');
        let level = 0;

        if (levelBadge) {
          // Extract level from badge class (e.g., "level-m3" -> 3)
          const levelMatch = levelBadge.className.match(/level-m(\d)/);
          level = levelMatch ? parseInt(levelMatch[1]) : 0;
        }

        // Show row if no filters active OR level matches active filters
        // Also show rows with level 0 (no level assigned) when any filter is active
        const shouldShow = activeMaturities.size === 0 ||
                          activeMaturities.size === 5 ||
                          activeMaturities.has(level) ||
                          (level === 0 && activeMaturities.size > 0);

        if (shouldShow) {
          row.style.display = '';
          totalVisible++;
        } else {
          row.style.display = 'none';
        }
      });

      // Hide empty groups (categories/layers with no visible metrics)
      document.querySelectorAll('.metrics-group').forEach(group => {
        const container = group.querySelector('.bullet-container');
        if (!container) return;

        const visibleRows = container.querySelectorAll('.bullet-row:not([style*="display: none"])');
        const countBadge = group.querySelector('.metrics-group-count');

        if (visibleRows.length === 0) {
          group.style.display = 'none';
        } else {
          group.style.display = '';
          // Update count in group header
          if (countBadge) {
            countBadge.textContent = visibleRows.length + ' metrics';
          }
        }
      });
    }

    // Toggle filter buttons
    document.querySelectorAll('.filter-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        btn.classList.toggle('active');
        applyMetricsFilters();
      });
    });

    // Apply filters after bullet charts are rendered
    const origRenderBulletCharts = renderBulletCharts;
    renderBulletCharts = function() {
      origRenderBulletCharts();
      setTimeout(applyMetricsFilters, 100);
    };
  </script>
`

// stackPageFooter is the shared HTML footer for stack pages.
const stackPageFooter = `
    {{if not .HideGeneratedBy}}
    <footer class="site-footer">
      <p>Generated by <a href="https://github.com/grokify/prism">PRISM</a></p>
    </footer>
    {{end}}
  </div>

  {{if .HasSiteNavJS}}
  <script type="module">
    // Configure navbar with stacks
    const navbar = document.getElementById('navbar');
    navbar.config = {
      baseUrl: '{{.BaseURL}}',
      brand: {
        name: '{{.SiteTitle}}',
        href: '{{.BaseURL}}/',
      },
      dropdowns: [
        {{range .AllStacks}}
        {
          id: '{{.BaseName}}',
          label: '{{.Stack.Metadata.Title}}',
          items: [
            { id: 'caps-by-cat', label: 'Capabilities by Category', href: '{{$.BaseURL}}/stacks/capabilities-by-category-{{.BaseName}}.html' },
            { id: 'caps-by-layer', label: 'Capabilities by Layer', href: '{{$.BaseURL}}/stacks/capabilities-by-layer-{{.BaseName}}.html' },
            {{if .Model}}
            { id: 'metrics-by-cat', label: 'Metrics by Category', href: '{{$.BaseURL}}/stacks/metrics-by-category-{{.BaseName}}.html' },
            { id: 'metrics-by-layer', label: 'Metrics by Layer', href: '{{$.BaseURL}}/stacks/metrics-by-layer-{{.BaseName}}.html' },
            {{end}}
          ],
        },
        {{end}}
      ],
    };

    // Theme toggle handling - sync navbar, header, badges, and page
    const themeToggle = document.getElementById('themeToggle');
    const header = document.getElementById('header');

    function applyTheme(theme) {
      document.documentElement.setAttribute('theme', theme);
      navbar?.setAttribute('theme', theme);
      header?.setAttribute('theme', theme);
      themeToggle?.setAttribute('theme', theme);
      document.querySelectorAll('wt-badge').forEach(el => el.setAttribute('theme', theme));
    }

    // Listen to theme toggle for changes
    themeToggle?.addEventListener('wt-theme-change', (e) => {
      const { resolvedTheme } = e.detail;
      applyTheme(resolvedTheme);
    });

    // Also listen to navbar for theme changes (backup)
    navbar?.addEventListener('wt-theme-change', (e) => {
      const { resolvedTheme } = e.detail;
      applyTheme(resolvedTheme);
    });
  </script>
  {{end}}
</body>
</html>`

// capsByLayerTemplate is the template for capabilities by layer page.
const capsByLayerTemplate = stackPageHeader + `
</head>
<body>
  <div class="site-container">
    <div class="site-header-row">
      {{if .HasSiteNavJS}}
      <wt-header id="header" title="{{.Title}}" {{if .Stack.Metadata.Version}}version="{{.Stack.Metadata.Version}}"{{end}} {{if .Stack.Metadata.Description}}description="{{.Stack.Metadata.Description}}"{{end}} theme="{{.Theme}}"></wt-header>
      <wt-theme-toggle id="themeToggle" variant="icon" theme="{{.Theme}}"></wt-theme-toggle>
      {{else}}
      <header class="fallback-header">
        <h1>{{.Title}}</h1>
        {{if .Stack.Metadata.Version}}<span class="version">v{{.Stack.Metadata.Version}}</span>{{end}}
        {{if .Stack.Metadata.Description}}<p>{{.Stack.Metadata.Description}}</p>{{end}}
      </header>
      {{end}}
    </div>
` + stackPageNav + stackFilterSection + `
    <main class="site-main">
      {{range .CapsByLayer}}
      <div class="layer" data-layer-id="{{.ID}}">
        <div class="layer-header">
          <span class="layer-title">{{.Name}}</span>
          <span class="layer-count">{{len .Capabilities}} capabilities</span>
        </div>
        <div class="capabilities-grid">
          {{$hasJS := $.HasSiteNavJS}}
          {{$capMat := $.CapMaturity}}
          {{$capSLI := $.CapSLICount}}
          {{range .Capabilities}}
          {{$matLevel := maturityLevel .ID $capMat}}
          {{$sliCount := sliCount .ID $capSLI}}
          <a href="{{$.BaseURL}}/capabilities/{{$.StackData.BaseName}}-{{.ID | kebab}}.html"
             class="capability-card"
             data-status="{{.Status}}"
             data-maturity="{{printf "%.0f" $matLevel}}"
             data-capability-id="{{.ID}}">
            {{if gt $sliCount 0}}<span class="metrics-indicator" title="{{$sliCount}} metrics">{{$sliCount}}</span>{{end}}
            <span class="capability-name">{{.Name}}</span>
            <div class="capability-badges">
              {{if $hasJS}}<wt-badge variant="{{.Status | statusVariant}}" size="sm">{{.Status}}</wt-badge>{{else}}<span class="status-badge status-{{.Status}}">{{.Status}}</span>{{end}}
              {{if gt $matLevel 0.0}}{{if $hasJS}}<wt-badge variant="m{{printf "%.0f" $matLevel}}" size="sm">M{{printf "%.0f" $matLevel}}</wt-badge>{{else}}<span class="maturity-badge maturity-m{{printf "%.0f" $matLevel}}">M{{printf "%.0f" $matLevel}}</span>{{end}}{{end}}
            </div>
          </a>
          {{end}}
        </div>
      </div>
      {{end}}

      {{if .Stack.Foundational}}
      <div class="layer layer--foundational">
        <div class="layer-header">
          <span class="layer-title">Foundational</span>
          <span class="layer-count">{{len .Stack.Foundational}} capabilities</span>
        </div>
        <div class="capabilities-grid">
          {{$hasJS := $.HasSiteNavJS}}
          {{$capMat := $.CapMaturity}}
          {{$capSLI := $.CapSLICount}}
          {{range .Stack.Foundational}}
          {{$matLevel := maturityLevel .ID $capMat}}
          {{$sliCount := sliCount .ID $capSLI}}
          <a href="{{$.BaseURL}}/capabilities/{{$.StackData.BaseName}}-{{.ID | kebab}}.html"
             class="capability-card"
             data-status="{{.Status}}"
             data-maturity="{{printf "%.0f" $matLevel}}"
             data-capability-id="{{.ID}}">
            {{if gt $sliCount 0}}<span class="metrics-indicator" title="{{$sliCount}} metrics">{{$sliCount}}</span>{{end}}
            <span class="capability-name">{{.Name}}</span>
            <div class="capability-badges">
              {{if $hasJS}}<wt-badge variant="{{.Status | statusVariant}}" size="sm">{{.Status}}</wt-badge>{{else}}<span class="status-badge status-{{.Status}}">{{.Status}}</span>{{end}}
              {{if gt $matLevel 0.0}}{{if $hasJS}}<wt-badge variant="m{{printf "%.0f" $matLevel}}" size="sm">M{{printf "%.0f" $matLevel}}</wt-badge>{{else}}<span class="maturity-badge maturity-m{{printf "%.0f" $matLevel}}">M{{printf "%.0f" $matLevel}}</span>{{end}}{{end}}
            </div>
          </a>
          {{end}}
        </div>
      </div>
      {{end}}
    </main>
` + capabilityFilterScript + stackPageFooter

// capsByCategoryTemplate is the template for capabilities by category page.
const capsByCategoryTemplate = stackPageHeader + `
</head>
<body>
  <div class="site-container">
    <div class="site-header-row">
      {{if .HasSiteNavJS}}
      <wt-header id="header" title="{{.Title}}" {{if .Stack.Metadata.Version}}version="{{.Stack.Metadata.Version}}"{{end}} {{if .Stack.Metadata.Description}}description="{{.Stack.Metadata.Description}}"{{end}} theme="{{.Theme}}"></wt-header>
      <wt-theme-toggle id="themeToggle" variant="icon" theme="{{.Theme}}"></wt-theme-toggle>
      {{else}}
      <header class="fallback-header">
        <h1>{{.Title}}</h1>
        {{if .Stack.Metadata.Version}}<span class="version">v{{.Stack.Metadata.Version}}</span>{{end}}
        {{if .Stack.Metadata.Description}}<p>{{.Stack.Metadata.Description}}</p>{{end}}
      </header>
      {{end}}
    </div>
` + stackPageNav + stackFilterSection + `
    <main class="site-main">
      {{range .CapsByCategory}}
      <div class="layer" data-category-id="{{.ID}}">
        <div class="layer-header">
          <span class="layer-title">{{.Name}}</span>
          <span class="layer-count">{{len .Capabilities}} capabilities</span>
        </div>
        <div class="capabilities-grid">
          {{$hasJS := $.HasSiteNavJS}}
          {{$capMat := $.CapMaturity}}
          {{$capSLI := $.CapSLICount}}
          {{range .Capabilities}}
          {{$matLevel := maturityLevel .ID $capMat}}
          {{$sliCount := sliCount .ID $capSLI}}
          <a href="{{$.BaseURL}}/capabilities/{{$.StackData.BaseName}}-{{.ID | kebab}}.html"
             class="capability-card"
             data-status="{{.Status}}"
             data-maturity="{{printf "%.0f" $matLevel}}"
             data-capability-id="{{.ID}}">
            {{if gt $sliCount 0}}<span class="metrics-indicator" title="{{$sliCount}} metrics">{{$sliCount}}</span>{{end}}
            <span class="capability-name">{{.Name}}</span>
            <div class="capability-badges">
              {{if $hasJS}}<wt-badge variant="{{.Status | statusVariant}}" size="sm">{{.Status}}</wt-badge>{{else}}<span class="status-badge status-{{.Status}}">{{.Status}}</span>{{end}}
              {{if gt $matLevel 0.0}}{{if $hasJS}}<wt-badge variant="m{{printf "%.0f" $matLevel}}" size="sm">M{{printf "%.0f" $matLevel}}</wt-badge>{{else}}<span class="maturity-badge maturity-m{{printf "%.0f" $matLevel}}">M{{printf "%.0f" $matLevel}}</span>{{end}}{{end}}
            </div>
          </a>
          {{end}}
        </div>
      </div>
      {{end}}
    </main>
` + capabilityFilterScript + stackPageFooter

// metricsPageScripts contains the D3 bullet chart JavaScript for metrics pages.
const metricsPageScripts = `
  <script>
    // D3 Maturity Bullet Chart
    function d3MaturityBullet() {
      let width = 380, height = 30;
      function bullet(g) {
        g.each(function(d) {
          const g = d3.select(this);
          const x = d3.scale.linear().domain([0, 5]).range([0, width]);
          const rangeData = [
            { start: 0, end: 3, class: 's2' },
            { start: 3, end: 4, class: 's1' },
            { start: 4, end: 5, class: 's0' }
          ];
          g.selectAll('rect.range').data(rangeData).enter().append('rect')
            .attr('class', d => 'range ' + d.class)
            .attr('x', d => x(d.start))
            .attr('width', d => x(d.end) - x(d.start))
            .attr('height', height);
          const measurez = d.measures || [];
          if (measurez.length > 0) {
            const currentLevel = measurez[0];
            g.append('rect').attr('class', 'measure s0')
              .attr('x', 0).attr('width', x(currentLevel))
              .attr('height', height / 3).attr('y', height / 3);
            g.append('text').attr('class', 'measure-label')
              .attr('x', x(currentLevel) + 4).attr('y', height / 2 + 5)
              .style('font-size', '13px').style('font-weight', 'bold').style('fill', '#3b82f6')
              .text(currentLevel.toFixed(1));
          }
          const ticks = [1, 2, 3, 4, 5];
          const thresholds = d.thresholds || [];
          const thresholdByLevel = {};
          thresholds.forEach(t => { thresholdByLevel[t.level] = t.valueStr || ''; });
          const tickG = g.selectAll('g.tick').data(ticks).enter().append('g')
            .attr('class', 'tick').attr('transform', d => 'translate(' + x(d) + ',0)');
          tickG.append('line').attr('y1', height).attr('y2', height + 6)
            .style('stroke', '#666').style('stroke-width', '1px');
          tickG.append('text').attr('text-anchor', 'middle').attr('y', height + 16)
            .style('font-size', '11px').style('font-weight', 'bold').style('fill', 'var(--text-primary)')
            .text(d => 'M' + d);
          const hasThresholds = thresholds.length > 0;
          tickG.append('text').attr('text-anchor', 'middle').attr('y', height + 28)
            .style('font-size', '10px').style('fill', 'var(--text-secondary)')
            .text(d => thresholdByLevel[d] || (hasThresholds ? '-' : ''));
        });
      }
      bullet.width = function(x) { if (!arguments.length) return width; width = x; return bullet; };
      bullet.height = function(x) { if (!arguments.length) return height; height = x; return bullet; };
      return bullet;
    }

    function renderBulletCharts() {
      document.querySelectorAll('.bullet-container').forEach(container => {
        if (container.dataset.rendered) return;
        container.dataset.rendered = 'true';
        const metrics = JSON.parse(container.dataset.metrics || '[]');
        if (metrics.length === 0) return;
        metrics.forEach((d, i) => {
          const row = document.createElement('div');
          row.className = 'bullet-row';
          const currentLevel = d.measures && d.measures.length > 0 ? d.measures[0] : 0;
          const levelBadge = currentLevel > 0 ? '<span class="sli-level-badge level-m' + Math.floor(currentLevel) + '">M' + currentLevel.toFixed(1) + '</span>' : '';
          row.innerHTML = '<div class="bullet-label"><div class="bullet-label-title" title="' + d.title + '">' + d.title + '</div><div class="bullet-label-meta"><span class="bullet-label-subtitle">' + (d.subtitle || '') + '</span>' + levelBadge + '</div></div><div class="bullet-chart" id="bullet-' + container.id + '-' + i + '"></div>';
          container.appendChild(row);
        });
        setTimeout(() => {
          const labels = container.querySelectorAll('.bullet-label');
          let maxWidth = 0;
          labels.forEach(label => { maxWidth = Math.max(maxWidth, label.offsetWidth); });
          const uniformWidth = Math.ceil(maxWidth) + 16;
          labels.forEach(label => { label.style.flex = '0 0 ' + uniformWidth + 'px'; label.style.width = uniformWidth + 'px'; });
          setTimeout(() => {
            metrics.forEach((d, i) => {
              const chartContainer = document.getElementById('bullet-' + container.id + '-' + i);
              if (!chartContainer) return;
              const margin = {top: 5, right: 40, bottom: 35, left: 0};
              const width = chartContainer.offsetWidth - margin.left - margin.right;
              const height = 32;
              const chart = d3MaturityBullet().width(width).height(height);
              d3.select(chartContainer).append('svg').attr('class', 'bullet')
                .attr('width', width + margin.left + margin.right)
                .attr('height', height + margin.top + margin.bottom)
                .append('g').attr('transform', 'translate(' + margin.left + ',' + margin.top + ')')
                .datum(d).call(chart);
            });
          }, 0);
        }, 0);
      });
    }
    document.addEventListener('DOMContentLoaded', renderBulletCharts);
  </script>
`

// metricsByCategoryTemplate is the template for metrics by category page.
const metricsByCategoryTemplate = stackPageHeader + `
  <script src="https://d3js.org/d3.v3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.1/jspdf.plugin.autotable.min.js"></script>
  <style>
    .metrics-view-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .export-all-btn, .export-category-btn {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 6px 12px;
      font-size: 0.8rem;
      font-weight: 500;
      color: white;
      background: #3b82f6;
      border: none;
      border-radius: var(--radius-md);
      cursor: pointer;
      transition: background 0.2s ease;
    }
    .export-all-btn:hover, .export-category-btn:hover {
      background: #2563eb;
    }
    .export-category-btn {
      padding: 4px 8px;
      font-size: 0.75rem;
    }
    .export-all-btn svg, .export-category-btn svg {
      width: 14px;
      height: 14px;
    }
    .metrics-group-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }
  </style>
</head>
<body>
  <div class="site-container">
    <div class="site-header-row">
      {{if .HasSiteNavJS}}
      <wt-header id="header" title="{{.Title}}" {{if .Stack.Metadata.Version}}version="{{.Stack.Metadata.Version}}"{{end}} {{if .Stack.Metadata.Description}}description="{{.Stack.Metadata.Description}}"{{end}} theme="{{.Theme}}"></wt-header>
      <wt-theme-toggle id="themeToggle" variant="icon" theme="{{.Theme}}"></wt-theme-toggle>
      {{else}}
      <header class="fallback-header">
        <h1>{{.Title}}</h1>
        {{if .Stack.Metadata.Version}}<span class="version">v{{.Stack.Metadata.Version}}</span>{{end}}
        {{if .Stack.Metadata.Description}}<p>{{.Stack.Metadata.Description}}</p>{{end}}
      </header>
      {{end}}
    </div>
` + stackPageNav + metricsFilterSection + `
    <main class="site-main">
      <div class="metrics-view-header">
        <div class="bullet-legend">
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #fee2e2"></div><span>M1-M3</span></div>
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #fef3c7"></div><span>M4</span></div>
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #dcfce7"></div><span>M5</span></div>
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #3b82f6"></div><span>Current Level</span></div>
        </div>
        <div class="metrics-view-actions">
          <button class="export-all-btn" id="export-all-categories-btn" title="Export All Categories to PDF">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            Export All Categories
          </button>
        </div>
      </div>
      {{range .MetricsByCat}}
      <div class="metrics-group" data-category-id="{{.ID}}" data-category-name="{{.Name}}">
        <div class="metrics-group-header">
          <span class="metrics-group-title">{{.Name}}</span>
          <div class="metrics-group-actions">
            <span class="metrics-group-count">{{len .SLIs}} metrics</span>
            <button class="export-category-btn" data-category="{{.ID}}" title="Export Category to PDF">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              PDF
            </button>
          </div>
        </div>
        <div class="bullet-container" id="metrics-cat-{{.ID}}" data-metrics="{{.SLIs | json}}"></div>
      </div>
      {{end}}
    </main>
` + metricsPageScripts + metricsFilterScript + `
  <script>
    // PDF Export for Category Views
    var categoryMetricsData = {
      {{range .MetricsByCat}}
      "{{.ID}}": { name: "{{.Name}}", metrics: {{.SLIs | json}} },
      {{end}}
    };

    function exportCategoryToPDF(categoryID) {
      var categoryData = categoryMetricsData[categoryID];
      if (!categoryData) return;

      var jsPDF = window.jspdf.jsPDF;
      var doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

      var exportDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
      });

      // Header
      doc.setFontSize(16);
      doc.setFont(undefined, 'bold');
      doc.text('Category Maturity: ' + categoryData.name, 14, 15);
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text('Generated: ' + exportDate, 14, 22);
      doc.text('{{.Title}}', 14, 27);

      // Prepare table data
      var tableData = categoryData.metrics.map(function(m) {
        var level = m.measures && m.measures.length > 0 ? m.measures[0] : 0;
        var thresholds = m.thresholds || [];
        var t = {};
        thresholds.forEach(function(th) { t[th.level] = th.valueStr || '-'; });
        return [
          m.title || '',
          level > 0 ? 'M' + level.toFixed(1) : '-',
          t[1] || '-',
          t[2] || '-',
          t[3] || '-',
          t[4] || '-',
          t[5] || '-'
        ];
      });

      doc.autoTable({
        startY: 32,
        head: [['Metric', 'Current', 'M1', 'M2', 'M3', 'M4', 'M5']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8 },
        columnStyles: {
          0: { cellWidth: 80 },
          1: { cellWidth: 25, halign: 'center' },
          2: { cellWidth: 30, halign: 'center' },
          3: { cellWidth: 30, halign: 'center' },
          4: { cellWidth: 30, halign: 'center' },
          5: { cellWidth: 30, halign: 'center' },
          6: { cellWidth: 30, halign: 'center' }
        }
      });

      var dateStr = new Date().toISOString().split('T')[0];
      doc.save('category-' + categoryID + '-' + dateStr + '.pdf');
    }

    function exportAllCategoriesToPDF() {
      var jsPDF = window.jspdf.jsPDF;
      var doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

      var exportDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
      });

      // Title page
      doc.setFontSize(20);
      doc.setFont(undefined, 'bold');
      doc.text('Category Maturity Report', 14, 20);
      doc.setFontSize(14);
      doc.setFont(undefined, 'normal');
      doc.text('{{.Title}}', 14, 30);
      doc.setFontSize(10);
      doc.text('Generated: ' + exportDate, 14, 40);

      // Summary table
      var summaryData = [];
      for (var catID in categoryMetricsData) {
        var cat = categoryMetricsData[catID];
        var avgLevel = 0;
        var count = 0;
        cat.metrics.forEach(function(m) {
          if (m.measures && m.measures.length > 0) {
            avgLevel += m.measures[0];
            count++;
          }
        });
        avgLevel = count > 0 ? avgLevel / count : 0;
        summaryData.push([cat.name, cat.metrics.length + ' metrics', avgLevel > 0 ? 'M' + avgLevel.toFixed(1) : '-']);
      }

      doc.autoTable({
        startY: 50,
        head: [['Category', 'Metrics', 'Avg Level']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] }
      });

      // Each category on new page
      for (var catID in categoryMetricsData) {
        doc.addPage();
        var categoryData = categoryMetricsData[catID];

        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text('Category: ' + categoryData.name, 14, 15);

        var tableData = categoryData.metrics.map(function(m) {
          var level = m.measures && m.measures.length > 0 ? m.measures[0] : 0;
          var thresholds = m.thresholds || [];
          var t = {};
          thresholds.forEach(function(th) { t[th.level] = th.valueStr || '-'; });
          return [
            m.title || '',
            level > 0 ? 'M' + level.toFixed(1) : '-',
            t[1] || '-',
            t[2] || '-',
            t[3] || '-',
            t[4] || '-',
            t[5] || '-'
          ];
        });

        doc.autoTable({
          startY: 22,
          head: [['Metric', 'Current', 'M1', 'M2', 'M3', 'M4', 'M5']],
          body: tableData,
          theme: 'grid',
          headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold', fontSize: 9 },
          bodyStyles: { fontSize: 8 },
          columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 25, halign: 'center' },
            2: { cellWidth: 30, halign: 'center' },
            3: { cellWidth: 30, halign: 'center' },
            4: { cellWidth: 30, halign: 'center' },
            5: { cellWidth: 30, halign: 'center' },
            6: { cellWidth: 30, halign: 'center' }
          }
        });
      }

      var dateStr = new Date().toISOString().split('T')[0];
      doc.save('all-categories-' + dateStr + '.pdf');
    }

    // Event listeners for export buttons
    document.querySelectorAll('.export-category-btn').forEach(function(btn) {
      btn.addEventListener('click', function() {
        exportCategoryToPDF(btn.dataset.category);
      });
    });

    document.getElementById('export-all-categories-btn')?.addEventListener('click', exportAllCategoriesToPDF);
  </script>
` + stackPageFooter

// metricsByLayerTemplate is the template for metrics by layer page.
const metricsByLayerTemplate = stackPageHeader + `
  <script src="https://d3js.org/d3.v3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.1/jspdf.plugin.autotable.min.js"></script>
  <style>
    .metrics-view-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .export-all-btn, .export-layer-btn {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 6px 12px;
      font-size: 0.8rem;
      font-weight: 500;
      color: white;
      background: #3b82f6;
      border: none;
      border-radius: var(--radius-md);
      cursor: pointer;
      transition: background 0.2s ease;
    }
    .export-all-btn:hover, .export-layer-btn:hover {
      background: #2563eb;
    }
    .export-layer-btn {
      padding: 4px 8px;
      font-size: 0.75rem;
    }
    .export-all-btn svg, .export-layer-btn svg {
      width: 14px;
      height: 14px;
    }
    .metrics-group-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }
  </style>
</head>
<body>
  <div class="site-container">
    <div class="site-header-row">
      {{if .HasSiteNavJS}}
      <wt-header id="header" title="{{.Title}}" {{if .Stack.Metadata.Version}}version="{{.Stack.Metadata.Version}}"{{end}} {{if .Stack.Metadata.Description}}description="{{.Stack.Metadata.Description}}"{{end}} theme="{{.Theme}}"></wt-header>
      <wt-theme-toggle id="themeToggle" variant="icon" theme="{{.Theme}}"></wt-theme-toggle>
      {{else}}
      <header class="fallback-header">
        <h1>{{.Title}}</h1>
        {{if .Stack.Metadata.Version}}<span class="version">v{{.Stack.Metadata.Version}}</span>{{end}}
        {{if .Stack.Metadata.Description}}<p>{{.Stack.Metadata.Description}}</p>{{end}}
      </header>
      {{end}}
    </div>
` + stackPageNav + metricsFilterSection + `
    <main class="site-main">
      <div class="metrics-view-header">
        <div class="bullet-legend">
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #fee2e2"></div><span>M1-M3</span></div>
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #fef3c7"></div><span>M4</span></div>
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #dcfce7"></div><span>M5</span></div>
          <div class="bullet-legend-item"><div class="bullet-legend-swatch" style="background: #3b82f6"></div><span>Current Level</span></div>
        </div>
        <div class="metrics-view-actions">
          <button class="export-all-btn" id="export-all-layers-btn" title="Export All Layers to PDF">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            Export All Layers
          </button>
        </div>
      </div>
      {{range .MetricsByLayer}}
      <div class="metrics-group" data-layer-id="{{.ID}}" data-layer-name="{{.Name}}">
        <div class="metrics-group-header">
          <span class="metrics-group-title">{{.Name}}</span>
          <div class="metrics-group-actions">
            <span class="metrics-group-count">{{len .SLIs}} metrics</span>
            <button class="export-layer-btn" data-layer="{{.ID}}" title="Export Layer to PDF">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              PDF
            </button>
          </div>
        </div>
        <div class="bullet-container" id="metrics-layer-{{.ID}}" data-metrics="{{.SLIs | json}}"></div>
      </div>
      {{end}}
    </main>
` + metricsPageScripts + metricsFilterScript + `
  <script>
    // PDF Export for Layer Views
    var layerMetricsData = {
      {{range .MetricsByLayer}}
      "{{.ID}}": { name: "{{.Name}}", metrics: {{.SLIs | json}} },
      {{end}}
    };

    function exportLayerToPDF(layerID) {
      var layerData = layerMetricsData[layerID];
      if (!layerData) return;

      var jsPDF = window.jspdf.jsPDF;
      var doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

      var exportDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
      });

      // Header
      doc.setFontSize(16);
      doc.setFont(undefined, 'bold');
      doc.text('Layer Maturity: ' + layerData.name, 14, 15);
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text('Generated: ' + exportDate, 14, 22);
      doc.text('{{.Title}}', 14, 27);

      // Prepare table data
      var tableData = layerData.metrics.map(function(m) {
        var level = m.measures && m.measures.length > 0 ? m.measures[0] : 0;
        var thresholds = m.thresholds || [];
        var t = {};
        thresholds.forEach(function(th) { t[th.level] = th.valueStr || '-'; });
        return [
          m.title || '',
          level > 0 ? 'M' + level.toFixed(1) : '-',
          t[1] || '-',
          t[2] || '-',
          t[3] || '-',
          t[4] || '-',
          t[5] || '-'
        ];
      });

      doc.autoTable({
        startY: 32,
        head: [['Metric', 'Current', 'M1', 'M2', 'M3', 'M4', 'M5']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8 },
        columnStyles: {
          0: { cellWidth: 80 },
          1: { cellWidth: 25, halign: 'center' },
          2: { cellWidth: 30, halign: 'center' },
          3: { cellWidth: 30, halign: 'center' },
          4: { cellWidth: 30, halign: 'center' },
          5: { cellWidth: 30, halign: 'center' },
          6: { cellWidth: 30, halign: 'center' }
        }
      });

      var dateStr = new Date().toISOString().split('T')[0];
      doc.save('layer-' + layerID + '-' + dateStr + '.pdf');
    }

    function exportAllLayersToPDF() {
      var jsPDF = window.jspdf.jsPDF;
      var doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

      var exportDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
      });

      // Title page
      doc.setFontSize(20);
      doc.setFont(undefined, 'bold');
      doc.text('Layer Maturity Report', 14, 20);
      doc.setFontSize(14);
      doc.setFont(undefined, 'normal');
      doc.text('{{.Title}}', 14, 30);
      doc.setFontSize(10);
      doc.text('Generated: ' + exportDate, 14, 40);

      // Summary table
      var summaryData = [];
      for (var layerID in layerMetricsData) {
        var layer = layerMetricsData[layerID];
        var avgLevel = 0;
        var count = 0;
        layer.metrics.forEach(function(m) {
          if (m.measures && m.measures.length > 0) {
            avgLevel += m.measures[0];
            count++;
          }
        });
        avgLevel = count > 0 ? avgLevel / count : 0;
        summaryData.push([layer.name, layer.metrics.length + ' metrics', avgLevel > 0 ? 'M' + avgLevel.toFixed(1) : '-']);
      }

      doc.autoTable({
        startY: 50,
        head: [['Layer', 'Metrics', 'Avg Level']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] }
      });

      // Each layer on new page
      for (var layerID in layerMetricsData) {
        doc.addPage();
        var layerData = layerMetricsData[layerID];

        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text('Layer: ' + layerData.name, 14, 15);

        var tableData = layerData.metrics.map(function(m) {
          var level = m.measures && m.measures.length > 0 ? m.measures[0] : 0;
          var thresholds = m.thresholds || [];
          var t = {};
          thresholds.forEach(function(th) { t[th.level] = th.valueStr || '-'; });
          return [
            m.title || '',
            level > 0 ? 'M' + level.toFixed(1) : '-',
            t[1] || '-',
            t[2] || '-',
            t[3] || '-',
            t[4] || '-',
            t[5] || '-'
          ];
        });

        doc.autoTable({
          startY: 22,
          head: [['Metric', 'Current', 'M1', 'M2', 'M3', 'M4', 'M5']],
          body: tableData,
          theme: 'grid',
          headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold', fontSize: 9 },
          bodyStyles: { fontSize: 8 },
          columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 25, halign: 'center' },
            2: { cellWidth: 30, halign: 'center' },
            3: { cellWidth: 30, halign: 'center' },
            4: { cellWidth: 30, halign: 'center' },
            5: { cellWidth: 30, halign: 'center' },
            6: { cellWidth: 30, halign: 'center' }
          }
        });
      }

      var dateStr = new Date().toISOString().split('T')[0];
      doc.save('all-layers-' + dateStr + '.pdf');
    }

    // Event listeners for export buttons
    document.querySelectorAll('.export-layer-btn').forEach(function(btn) {
      btn.addEventListener('click', function() {
        exportLayerToPDF(btn.dataset.layer);
      });
    });

    document.getElementById('export-all-layers-btn')?.addEventListener('click', exportAllLayersToPDF);
  </script>
` + stackPageFooter

// metricsTableTemplate is the template for the metrics threshold matrix table.
const metricsTableTemplate = stackPageHeader + `
  <!-- Tabulator CSS -->
  <link href="https://unpkg.com/tabulator-tables@6.3.1/dist/css/tabulator.min.css" rel="stylesheet">
  <style>
    .metrics-table-container {
      margin-top: 1rem;
      background: var(--bg-primary);
      border-radius: var(--radius-lg);
      padding: 1rem;
      box-shadow: var(--shadow-sm);
    }
    .metrics-table-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1rem;
      flex-wrap: wrap;
      gap: 12px;
    }
    .metrics-table-title {
      font-size: 1.25rem;
      font-weight: 600;
      color: var(--text-primary);
    }
    .metrics-table-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .metrics-table-count {
      font-size: 0.875rem;
      color: var(--text-muted);
    }
    .export-btn {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 8px 16px;
      font-size: 0.875rem;
      font-weight: 500;
      color: white;
      background: #3b82f6;
      border: none;
      border-radius: var(--radius-md);
      cursor: pointer;
      transition: background 0.2s ease;
    }
    .export-btn:hover {
      background: #2563eb;
    }
    .export-btn svg {
      width: 16px;
      height: 16px;
    }
    /* Tabulator theme overrides for dark mode */
    [theme="dark"] .tabulator {
      background-color: var(--bg-secondary);
      border-color: var(--border);
    }
    [theme="dark"] .tabulator-header {
      background-color: var(--bg-tertiary);
      border-color: var(--border);
    }
    [theme="dark"] .tabulator-header .tabulator-col {
      background-color: var(--bg-tertiary);
      border-color: var(--border);
    }
    [theme="dark"] .tabulator-header .tabulator-col-content {
      color: var(--text-primary);
    }
    [theme="dark"] .tabulator-row {
      background-color: var(--bg-secondary);
      border-color: var(--border);
    }
    [theme="dark"] .tabulator-row:nth-child(even) {
      background-color: var(--bg-tertiary);
    }
    [theme="dark"] .tabulator-row:hover {
      background-color: var(--bg-primary);
    }
    [theme="dark"] .tabulator-cell {
      color: var(--text-primary);
      border-color: var(--border);
    }
    [theme="dark"] .tabulator-header-filter input {
      background-color: var(--bg-primary);
      color: var(--text-primary);
      border-color: var(--border);
    }
    /* Maturity level cell styling */
    .tabulator-cell[data-level="1"],
    .tabulator-cell[data-level="2"],
    .tabulator-cell[data-level="3"] {
      background-color: rgba(254, 226, 226, 0.3);
    }
    .tabulator-cell[data-level="4"] {
      background-color: rgba(254, 243, 199, 0.3);
    }
    .tabulator-cell[data-level="5"] {
      background-color: rgba(220, 252, 231, 0.3);
    }
    /* Current level badge styling */
    .level-badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-weight: 600;
      font-size: 12px;
      color: white;
    }
    .level-badge.level-0 { background: #9ca3af; }
    .level-badge.level-1 { background: #ef4444; }
    .level-badge.level-2 { background: #f59e0b; }
    .level-badge.level-3 { background: #eab308; }
    .level-badge.level-4 { background: #22c55e; }
    .level-badge.level-5 { background: #3b82f6; }
    /* Target column styling - editable appearance */
    .tabulator-cell.editable-cell {
      background-color: rgba(59, 130, 246, 0.05);
      border: 1px dashed rgba(59, 130, 246, 0.3);
    }
    .tabulator-cell.editable-cell:hover {
      background-color: rgba(59, 130, 246, 0.1);
    }
    [theme="dark"] .tabulator-cell.editable-cell {
      background-color: rgba(59, 130, 246, 0.1);
      border: 1px dashed rgba(59, 130, 246, 0.4);
    }
    /* Column group headers */
    .tabulator-col-group-title {
      font-weight: 600;
      background: var(--bg-tertiary) !important;
    }
    /* Metrics filter buttons - dynamic colors */
    .metrics-filter-btn {
      padding: 6px 12px;
      font-size: 0.8rem;
      font-weight: 500;
      color: var(--text-muted);
      background: transparent;
      border: 2px solid var(--border);
      border-radius: var(--radius-md);
      cursor: pointer;
      transition: all 0.15s ease;
      opacity: 0.5;
    }
    .metrics-filter-btn:hover {
      opacity: 0.8;
    }
    .metrics-filter-btn.active {
      opacity: 1;
      color: white;
      font-weight: 600;
      background: var(--accent);
      border-color: var(--accent);
    }
    /* Category colors - cycle through a palette */
    .metrics-filter-btn[data-filter="category"] { border-color: #6366f1; color: #6366f1; }
    .metrics-filter-btn[data-filter="category"].active { background: #6366f1; border-color: #6366f1; color: white; }
    /* Tag colors */
    .metrics-filter-btn[data-filter="tags"] { border-color: #8b5cf6; color: #8b5cf6; }
    .metrics-filter-btn[data-filter="tags"].active { background: #8b5cf6; border-color: #8b5cf6; color: white; }
  </style>
</head>
<body>
  <div class="site-container">
    <div class="site-header-row">
      {{if .HasSiteNavJS}}
      <wt-header id="header" title="{{.Title}}" {{if .Stack.Metadata.Version}}version="{{.Stack.Metadata.Version}}"{{end}} {{if .Stack.Metadata.Description}}description="{{.Stack.Metadata.Description}}"{{end}} theme="{{.Theme}}"></wt-header>
      <wt-theme-toggle id="themeToggle" variant="icon" theme="{{.Theme}}"></wt-theme-toggle>
      {{else}}
      <header class="fallback-header">
        <h1>{{.Title}}</h1>
        {{if .Stack.Metadata.Version}}<span class="version">v{{.Stack.Metadata.Version}}</span>{{end}}
        {{if .Stack.Metadata.Description}}<p>{{.Stack.Metadata.Description}}</p>{{end}}
      </header>
      {{end}}
    </div>
` + stackPageNav + `
    <!-- Dynamic Filters Section -->
    <div class="filters-section" id="metrics-filters">
      <div class="filter-group">
        <div class="filter-label">Category</div>
        <div class="filter-buttons" id="category-filters"></div>
      </div>
      <div class="filter-group">
        <div class="filter-label">Tags</div>
        <div class="filter-buttons" id="tags-filters"></div>
      </div>
    </div>

    <main class="site-main">
      <div class="metrics-table-container">
        <div class="metrics-table-header">
          <span class="metrics-table-title">Maturity Targets & Thresholds</span>
          <div class="metrics-table-actions">
            <span class="metrics-table-count" id="metrics-count">{{len .ThresholdMatrix}} metrics</span>
            <button class="export-btn" id="export-pdf-btn" title="Export to PDF">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Export PDF
            </button>
          </div>
        </div>
        <div id="metrics-table"></div>
      </div>
    </main>

  <!-- Tabulator JS -->
  <script src="https://unpkg.com/tabulator-tables@6.3.1/dist/js/tabulator.min.js"></script>
  <!-- jsPDF for PDF export -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.1/jspdf.plugin.autotable.min.js"></script>
  <script>
    // Metrics data
    var metricsData = {{.ThresholdMatrixJSON}};

    // Get current quarter info for headers
    var now = new Date();
    var currentQuarter = Math.floor(now.getMonth() / 3) + 1;
    var currentYear = now.getFullYear();
    function getQuarterLabel(offset) {
      var q = currentQuarter + offset;
      var y = currentYear;
      while (q > 4) { q -= 4; y++; }
      while (q < 1) { q += 4; y--; }
      return 'Q' + q + ' ' + y;
    }
    var q1Label = getQuarterLabel(1);
    var q2Label = getQuarterLabel(2);

    // Extract unique categories and tags from data
    function extractUniqueValues(data, field, delimiter) {
      var values = new Set();
      data.forEach(function(row) {
        var val = row[field] || '';
        if (delimiter && val.includes(delimiter)) {
          val.split(delimiter).forEach(function(v) {
            var trimmed = v.trim();
            if (trimmed) values.add(trimmed);
          });
        } else if (val) {
          values.add(val);
        }
      });
      return Array.from(values).sort();
    }

    var uniqueCategories = extractUniqueValues(metricsData, 'category');
    var uniqueTags = extractUniqueValues(metricsData, 'tags', ',');

    // Track active filters
    var activeCategories = new Set(uniqueCategories);
    var activeTags = new Set(uniqueTags);

    // Generate filter buttons
    function generateFilterButtons(containerId, values, filterType, activeSet) {
      var container = document.getElementById(containerId);
      values.forEach(function(value) {
        var btn = document.createElement('button');
        btn.className = 'metrics-filter-btn active';
        btn.setAttribute('data-filter', filterType);
        btn.setAttribute('data-value', value);
        btn.textContent = value;
        btn.addEventListener('click', function() {
          btn.classList.toggle('active');
          if (btn.classList.contains('active')) {
            activeSet.add(value);
          } else {
            activeSet.delete(value);
          }
          applyFilters();
        });
        container.appendChild(btn);
      });
    }

    // Generate buttons after DOM is ready
    generateFilterButtons('category-filters', uniqueCategories, 'category', activeCategories);
    generateFilterButtons('tags-filters', uniqueTags, 'tags', activeTags);

    // Level badge formatter
    function levelFormatter(cell) {
      var value = cell.getValue();
      if (!value || value === 0) return '<span class="level-badge level-0">-</span>';
      var level = Math.floor(value);
      var display = value % 1 === 0 ? 'M' + value : 'M' + value.toFixed(1);
      return '<span class="level-badge level-' + level + '">' + display + '</span>';
    }

    // Threshold formatter with level styling
    function thresholdFormatter(cell) {
      var value = cell.getValue();
      var level = cell.getColumn().getField().replace('m', '');
      if (value && value !== '-') {
        cell.getElement().setAttribute('data-level', level);
      }
      return value || '-';
    }

    // Target editor - dropdown with M1-M5 options
    function targetEditor(cell, onRendered, success, cancel) {
      var currentValue = cell.getValue() || 0;
      var select = document.createElement('select');
      select.style.width = '100%';
      select.style.height = '100%';
      select.style.padding = '4px';
      select.style.fontSize = '13px';

      var options = [
        {value: 0, label: '-'},
        {value: 1, label: 'M1'},
        {value: 2, label: 'M2'},
        {value: 3, label: 'M3'},
        {value: 4, label: 'M4'},
        {value: 5, label: 'M5'}
      ];

      options.forEach(function(opt) {
        var option = document.createElement('option');
        option.value = opt.value;
        option.textContent = opt.label;
        if (opt.value == currentValue) option.selected = true;
        select.appendChild(option);
      });

      onRendered(function() {
        select.focus();
      });

      select.addEventListener('change', function() {
        success(parseFloat(select.value));
      });
      select.addEventListener('blur', function() {
        success(parseFloat(select.value));
      });

      return select;
    }

    // Custom filter function for Tabulator
    function metricsFilter(data) {
      // Category filter: row must match one of the active categories
      var categoryMatch = activeCategories.size === 0 || activeCategories.has(data.category);

      // Tags filter: row must have at least one tag that matches active tags
      var tagsMatch = true;
      if (activeTags.size > 0 && activeTags.size < uniqueTags.length) {
        var rowTags = (data.tags || '').split(',').map(function(t) { return t.trim(); });
        tagsMatch = rowTags.some(function(tag) { return activeTags.has(tag); });
      }

      return categoryMatch && tagsMatch;
    }

    // Initialize Tabulator
    var table = new Tabulator("#metrics-table", {
      data: metricsData,
      layout: "fitDataStretch",
      responsiveLayout: "collapse",
      pagination: false,
      movableColumns: true,
      resizableColumns: true,
      columnDefaults: {
        headerSort: true,
      },
      initialSort: [
        {column: "category", dir: "asc"},
        {column: "name", dir: "asc"}
      ],
      columns: [
        // Metric Info Group
        {title: "Category", field: "category", headerFilter: "input", minWidth: 100, frozen: true},
        {title: "SLI Name", field: "name", headerFilter: "input", minWidth: 180, frozen: true},
        {title: "Unit", field: "unit", width: 60, hozAlign: "center"},
        // Current State
        {title: "Current", field: "currentLevel", hozAlign: "center", formatter: levelFormatter, width: 80,
          titleFormatter: function() { return '<span title="Current Maturity Level">Current</span>'; }},
        {title: "Value", field: "currentValue", hozAlign: "center", width: 90},
        // Targets (Editable)
        {title: q1Label, field: "targetQ1", hozAlign: "center", formatter: levelFormatter, width: 85,
          editor: targetEditor, cssClass: "editable-cell",
          titleFormatter: function() { return '<span title="Target for ' + q1Label + ' (click to edit)">' + q1Label + '</span>'; }},
        {title: q2Label, field: "targetQ2", hozAlign: "center", formatter: levelFormatter, width: 85,
          editor: targetEditor, cssClass: "editable-cell",
          titleFormatter: function() { return '<span title="Target for ' + q2Label + ' (click to edit)">' + q2Label + '</span>'; }},
        // Thresholds
        {title: "M1", field: "m1", hozAlign: "center", formatter: thresholdFormatter, width: 80},
        {title: "M2", field: "m2", hozAlign: "center", formatter: thresholdFormatter, width: 80},
        {title: "M3", field: "m3", hozAlign: "center", formatter: thresholdFormatter, width: 80},
        {title: "M4", field: "m4", hozAlign: "center", formatter: thresholdFormatter, width: 80},
        {title: "M5", field: "m5", hozAlign: "center", formatter: thresholdFormatter, width: 80},
        // Hidden columns for filtering
        {title: "Tags", field: "tags", visible: false},
        {title: "Frameworks", field: "frameworks", visible: false},
      ],
    });

    // Apply filters to table
    function applyFilters() {
      table.setFilter(metricsFilter);
      // Update visible count
      var visibleCount = table.getDataCount("active");
      document.getElementById('metrics-count').textContent = visibleCount + ' metrics';
    }

    // PDF Export functionality
    document.getElementById('export-pdf-btn').addEventListener('click', function() {
      var jsPDF = window.jspdf.jsPDF;
      var doc = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4'
      });

      // Get current date for filename and header
      var exportDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
      });

      // Title
      doc.setFontSize(16);
      doc.setFont(undefined, 'bold');
      doc.text('Maturity Targets & Thresholds', 14, 15);
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text('Generated: ' + exportDate, 14, 22);
      doc.text('{{.Title}}', 14, 27);

      // Get visible data
      var visibleData = table.getData("active");

      // Prepare table data
      var tableData = visibleData.map(function(row) {
        return [
          row.category || '',
          row.name || '',
          row.currentLevel ? 'M' + row.currentLevel : '-',
          row.currentValue || '-',
          row.targetQ1 ? 'M' + row.targetQ1 : '-',
          row.targetQ2 ? 'M' + row.targetQ2 : '-',
          row.m1 || '-',
          row.m2 || '-',
          row.m3 || '-',
          row.m4 || '-',
          row.m5 || '-'
        ];
      });

      // Create table
      doc.autoTable({
        startY: 32,
        head: [['Category', 'SLI Name', 'Current', 'Value', q1Label, q2Label, 'M1', 'M2', 'M3', 'M4', 'M5']],
        body: tableData,
        theme: 'grid',
        headStyles: {
          fillColor: [59, 130, 246],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 8
        },
        bodyStyles: {
          fontSize: 7
        },
        columnStyles: {
          0: { cellWidth: 25 },
          1: { cellWidth: 45 },
          2: { cellWidth: 15, halign: 'center' },
          3: { cellWidth: 20, halign: 'center' },
          4: { cellWidth: 18, halign: 'center' },
          5: { cellWidth: 18, halign: 'center' },
          6: { cellWidth: 20, halign: 'center' },
          7: { cellWidth: 20, halign: 'center' },
          8: { cellWidth: 20, halign: 'center' },
          9: { cellWidth: 20, halign: 'center' },
          10: { cellWidth: 20, halign: 'center' }
        },
        didDrawPage: function(data) {
          // Footer
          doc.setFontSize(8);
          doc.setTextColor(128);
          doc.text('Page ' + doc.internal.getNumberOfPages(), data.settings.margin.left, doc.internal.pageSize.height - 10);
        }
      });

      // Save PDF
      var filename = 'maturity-targets-' + new Date().toISOString().split('T')[0] + '.pdf';
      doc.save(filename);
    });
  </script>
` + stackPageFooter

// capabilityPageTemplate is the HTML template for a capability detail page.
const capabilityPageTemplate = `<!DOCTYPE html>
<html lang="en" theme="{{.Theme}}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{.Capability.Name}} - {{.Stack.Metadata.Title}} - PRISM</title>
  <link rel="stylesheet" href="{{.BaseURL}}/assets/site.css">
  {{if .HasSiteNavJS}}<script type="module" src="{{.BaseURL}}/assets/site-nav.es.js"></script>{{end}}
  {{if gt .SLICount 0}}<script src="https://d3js.org/d3.v3.min.js"></script>{{end}}
</head>
<body>
  {{if .HasSiteNavJS}}
  <wt-navbar id="navbar" theme="{{.Theme}}"></wt-navbar>
  {{end}}

  <div class="site-container">
    <div class="site-header-row">
      {{if .HasSiteNavJS}}
      <wt-header
        id="header"
        title="{{.Capability.Name}}"
        {{if .Capability.FullName}}description="{{.Capability.FullName}}"{{end}}
        theme="{{.Theme}}"
      ></wt-header>
      <wt-theme-toggle id="themeToggle" variant="icon" theme="{{.Theme}}"></wt-theme-toggle>
      {{else}}
      <header class="fallback-header">
        <h1>{{.Capability.Name}}</h1>
        {{if .Capability.FullName}}<p>{{.Capability.FullName}}</p>{{end}}
      </header>
      {{end}}
    </div>

    {{if not .HasSiteNavJS}}
    <nav class="top-nav">
      <a href="{{.BaseURL}}/" class="top-nav-link">← {{.SiteTitle}}</a>
      <span class="top-nav-sep">›</span>
      <a href="{{.BaseURL}}/stacks/capabilities-by-category-{{.StackData.BaseName}}.html" class="top-nav-link">{{.Stack.Metadata.Title}}</a>
      <span class="top-nav-sep">›</span>
      <span class="top-nav-current">{{.Capability.Name}}</span>
    </nav>
    {{end}}

    <main class="site-main">
      <section class="capability-detail">
        <div class="capability-meta">
          <div class="meta-row">
            <span class="meta-label">Status</span>
            {{if .HasSiteNavJS}}<wt-badge variant="{{.Capability.Status}}" theme="{{.Theme}}">{{.Capability.Status}}</wt-badge>{{else}}<span class="status-badge status-{{.Capability.Status}}">{{.Capability.Status}}</span>{{end}}
          </div>
          {{if .Capability.Owner}}
          <div class="meta-row">
            <span class="meta-label">Owner</span>
            <span class="meta-value">{{.Capability.Owner}}</span>
          </div>
          {{end}}
          {{if .Capability.LayerID}}
          <div class="meta-row">
            <span class="meta-label">Layer</span>
            <span class="meta-value">{{.Capability.LayerID}}</span>
          </div>
          {{end}}
          {{if gt .MaturityLevel 0.0}}
          <div class="meta-row">
            <span class="meta-label">Maturity</span>
            {{if .HasSiteNavJS}}<wt-badge variant="m{{printf "%.0f" .MaturityLevel}}" theme="{{.Theme}}">M{{printf "%.0f" .MaturityLevel}}</wt-badge>{{else}}<span class="maturity-badge maturity-m{{printf "%.0f" .MaturityLevel}}">M{{printf "%.0f" .MaturityLevel}}</span>{{end}}
          </div>
          {{end}}
          {{if gt .SLICount 0}}
          <div class="meta-row">
            <span class="meta-label">SLIs</span>
            <span class="meta-value">{{.SLICount}} indicators</span>
          </div>
          {{end}}
        </div>

        {{if .Capability.Description}}
        <div class="capability-description">
          <h2>Description</h2>
          <p>{{.Capability.Description}}</p>
        </div>
        {{end}}

        {{if .Capability.Dependencies}}
        <div class="capability-dependencies">
          <h2>Dependencies</h2>
          <ul class="dependency-list">
            {{range .Capability.Dependencies}}
            <li>
              <a href="{{$.BaseURL}}/capabilities/{{$.StackData.BaseName}}-{{. | kebab}}.html">{{.}}</a>
            </li>
            {{end}}
          </ul>
        </div>
        {{end}}

        {{if gt .SLICount 0}}
        <div class="capability-slis">
          <h2>Service Level Indicators</h2>
          <div class="bullet-legend">
            <div class="bullet-legend-item">
              <div class="bullet-legend-swatch" style="background: #fee2e2"></div>
              <span>M1-M3</span>
            </div>
            <div class="bullet-legend-item">
              <div class="bullet-legend-swatch" style="background: #fef3c7"></div>
              <span>M4</span>
            </div>
            <div class="bullet-legend-item">
              <div class="bullet-legend-swatch" style="background: #dcfce7"></div>
              <span>M5</span>
            </div>
            <div class="bullet-legend-item">
              <div class="bullet-legend-swatch" style="background: #3b82f6"></div>
              <span>Current</span>
            </div>
          </div>
          <div class="bullet-container" id="sli-bullets"></div>
        </div>
        {{end}}
      </section>
    </main>

    {{if not .HideGeneratedBy}}
    <footer class="site-footer">
      <p>Generated by <a href="https://github.com/grokify/prism">PRISM</a></p>
    </footer>
    {{end}}
  </div>

  {{if gt .SLICount 0}}
  <script>
    // SLI Bullet Chart Data
    const sliBullets = {{.SLIBullets | json}};

    // D3 Maturity Bullet Chart - specialized for M1-M5 levels
    function d3MaturityBullet() {
      let width = 380;
      let height = 30;

      function bullet(g) {
        g.each(function(d) {
          const g = d3.select(this);

          // Fixed scale 0-5 for maturity levels
          const x = d3.scale.linear()
              .domain([0, 5])
              .range([0, width]);

          // Background ranges (colored zones)
          const rangeData = [
            { start: 0, end: 3, class: 's2' },   // M1-M3: red
            { start: 3, end: 4, class: 's1' },   // M4: yellow
            { start: 4, end: 5, class: 's0' }    // M5: green
          ];

          g.selectAll('rect.range')
              .data(rangeData)
            .enter().append('rect')
              .attr('class', d => 'range ' + d.class)
              .attr('x', d => x(d.start))
              .attr('width', d => x(d.end) - x(d.start))
              .attr('height', height);

          // Measure bar (current level)
          const measurez = d.measures || [];
          if (measurez.length > 0) {
            const currentLevel = measurez[0];
            g.append('rect')
                .attr('class', 'measure s0')
                .attr('x', 0)
                .attr('width', x(currentLevel))
                .attr('height', height / 3)
                .attr('y', height / 3);

            // Current level label on bar
            g.append('text')
                .attr('class', 'measure-label')
                .attr('x', x(currentLevel) + 4)
                .attr('y', height / 2 + 5)
                .style('font-size', '13px')
                .style('font-weight', 'bold')
                .style('fill', '#3b82f6')
                .text(currentLevel.toFixed(1));
          }

          // Target marker
          const markerz = d.markers || [];
          markerz.forEach(m => {
            g.append('line')
                .attr('class', 'marker')
                .attr('x1', x(m))
                .attr('x2', x(m))
                .attr('y1', height / 6)
                .attr('y2', height * 5 / 6);
          });

          // M1-M5 tick marks and labels with thresholds
          const ticks = [1, 2, 3, 4, 5];
          const thresholds = d.thresholds || [];

          // Create threshold lookup by level
          const thresholdByLevel = {};
          thresholds.forEach(t => {
            thresholdByLevel[t.level] = t.valueStr || '';
          });

          const tickG = g.selectAll('g.tick')
              .data(ticks)
            .enter().append('g')
              .attr('class', 'tick')
              .attr('transform', d => 'translate(' + x(d) + ',0)');

          tickG.append('line')
              .attr('y1', height)
              .attr('y2', height + 6)
              .style('stroke', '#666')
              .style('stroke-width', '1px');

          // Level label (M1, M2, etc.)
          tickG.append('text')
              .attr('text-anchor', 'middle')
              .attr('y', height + 16)
              .style('font-size', '11px')
              .style('font-weight', 'bold')
              .style('fill', 'var(--text-primary)')
              .text(d => 'M' + d);

          // Threshold value below level label
          const hasThresholds = thresholds.length > 0;
          tickG.append('text')
              .attr('text-anchor', 'middle')
              .attr('y', height + 28)
              .style('font-size', '10px')
              .style('fill', 'var(--text-secondary)')
              .text(d => thresholdByLevel[d] || (hasThresholds ? '-' : ''));
        });
      }

      bullet.width = function(x) {
        if (!arguments.length) return width;
        width = x;
        return bullet;
      };

      bullet.height = function(x) {
        if (!arguments.length) return height;
        height = x;
        return bullet;
      };

      return bullet;
    }

    // Render SLI bullets
    function renderSLIBullets() {
      const container = document.getElementById('sli-bullets');
      if (!container || !sliBullets || sliBullets.length === 0) return;

      // Create bullet rows with HTML labels and SVG charts
      sliBullets.forEach((d, i) => {
        const row = document.createElement('div');
        row.className = 'bullet-row';
        row.innerHTML = ` + "`" + `
          <div class="bullet-label">
            <div class="bullet-label-title" title="${d.title}">${d.title}</div>
            <div class="bullet-label-subtitle">${d.subtitle || ''}</div>
          </div>
          <div class="bullet-chart" id="bullet-chart-${i}"></div>
        ` + "`" + `;
        container.appendChild(row);
      });

      // Calculate max label width and apply uniform width
      setTimeout(() => {
        const labels = container.querySelectorAll('.bullet-label');
        let maxWidth = 0;
        labels.forEach(label => {
          maxWidth = Math.max(maxWidth, label.offsetWidth);
        });
        // Add padding and apply uniform width
        const uniformWidth = Math.ceil(maxWidth) + 16;
        labels.forEach(label => {
          label.style.flex = '0 0 ' + uniformWidth + 'px';
          label.style.width = uniformWidth + 'px';
        });

        // Render SVG bullet charts after layout is complete
        setTimeout(() => {
          sliBullets.forEach((d, i) => {
            const chartContainer = document.getElementById('bullet-chart-' + i);
            if (!chartContainer) return;

            const margin = {top: 5, right: 40, bottom: 35, left: 0};
            const width = chartContainer.offsetWidth - margin.left - margin.right;
            const height = 32;

            const chart = d3MaturityBullet().width(width).height(height);

            d3.select(chartContainer).append('svg')
                .attr('class', 'bullet')
                .attr('width', width + margin.left + margin.right)
                .attr('height', height + margin.top + margin.bottom)
              .append('g')
                .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')')
                .datum(d)
                .call(chart);
          });
        }, 0);
      }, 0);
    }

    // Initialize
    document.addEventListener('DOMContentLoaded', renderSLIBullets);
  </script>
  {{end}}

  {{if .HasSiteNavJS}}
  <script type="module">
    // Configure navbar with stacks
    const navbar = document.getElementById('navbar');
    navbar.config = {
      baseUrl: '{{.BaseURL}}',
      brand: {
        name: '{{.SiteTitle}}',
        href: '{{.BaseURL}}/',
      },
      dropdowns: [
        {{range .AllStacks}}
        {
          id: '{{.BaseName}}',
          label: '{{.Stack.Metadata.Title}}',
          items: [
            { id: 'caps-by-cat', label: 'Capabilities by Category', href: '{{$.BaseURL}}/stacks/capabilities-by-category-{{.BaseName}}.html' },
            { id: 'caps-by-layer', label: 'Capabilities by Layer', href: '{{$.BaseURL}}/stacks/capabilities-by-layer-{{.BaseName}}.html' },
            {{if .Model}}
            { id: 'metrics-by-cat', label: 'Metrics by Category', href: '{{$.BaseURL}}/stacks/metrics-by-category-{{.BaseName}}.html' },
            { id: 'metrics-by-layer', label: 'Metrics by Layer', href: '{{$.BaseURL}}/stacks/metrics-by-layer-{{.BaseName}}.html' },
            {{end}}
          ],
        },
        {{end}}
      ],
    };

    // Theme toggle handling - sync navbar, header, badges, and page
    const header = document.getElementById('header');
    const themeToggle = document.getElementById('themeToggle');

    function applyTheme(theme) {
      document.documentElement.setAttribute('theme', theme);
      navbar?.setAttribute('theme', theme);
      header?.setAttribute('theme', theme);
      themeToggle?.setAttribute('theme', theme);
      document.querySelectorAll('wt-badge').forEach(el => el.setAttribute('theme', theme));
    }

    // Listen to theme toggle for changes
    themeToggle?.addEventListener('wt-theme-change', (e) => {
      const { resolvedTheme } = e.detail;
      applyTheme(resolvedTheme);
    });

    // Also listen to navbar for theme changes (backup)
    navbar?.addEventListener('wt-theme-change', (e) => {
      const { resolvedTheme } = e.detail;
      applyTheme(resolvedTheme);
    });
  </script>
  {{end}}
</body>
</html>`

// siteCSS is the embedded CSS for the generated site.
const siteCSS = `
/* Base styles */
*, *::before, *::after {
  box-sizing: border-box;
}

/* Light theme (default) */
:root,
[theme="light"] {
  --bg-primary: #ffffff;
  --bg-secondary: #f8fafc;
  --bg-tertiary: #f1f5f9;
  --text-primary: #0f172a;
  --text-secondary: #334155;
  --text-muted: #64748b;
  --border: #cbd5e1;
  --accent: #0891b2;
  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.08);
  --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.12);
}

/* Dark theme */
[theme="dark"] {
  --bg-primary: #0f172a;
  --bg-secondary: #1e293b;
  --bg-tertiary: #334155;
  --text-primary: #f1f5f9;
  --text-secondary: #cbd5e1;
  --text-muted: #64748b;
  --border: #475569;
  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.3);
  --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.4);
}

/* System preference fallback */
@media (prefers-color-scheme: dark) {
  :root:not([theme="light"]) {
    --bg-primary: #0f172a;
    --bg-secondary: #1e293b;
    --bg-tertiary: #334155;
    --text-primary: #f1f5f9;
    --text-secondary: #cbd5e1;
    --text-muted: #64748b;
    --border: #475569;
    --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.3);
    --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.4);
  }
}

body {
  margin: 0;
  padding: 0;
  font-family: system-ui, -apple-system, sans-serif;
  background: var(--bg-primary);
  color: var(--text-primary);
  min-height: 100vh;
  transition: background 0.2s ease, color 0.2s ease;
}

/* Header row with theme toggle */
.site-header-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
}

.site-header-row wt-header {
  flex: 1;
}

.site-header-row wt-theme-toggle {
  flex-shrink: 0;
  margin-top: 8px;
}

a {
  color: var(--accent);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* Site layout */
.site-container {
  max-width: 1400px;
  margin: 0 auto;
  padding: 24px;
}

.site-main {
  margin-top: 24px;
}

.site-footer {
  margin-top: 48px;
  padding-top: 24px;
  border-top: 1px solid var(--border);
  text-align: center;
  color: var(--text-muted);
  font-size: 0.875rem;
}

/* Section titles */
.section-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin: 0 0 16px;
  color: var(--text-primary);
}

/* Cards grid */
.cards-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 16px;
}

/* Stack card */
.stack-card {
  display: block;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 20px;
  text-decoration: none;
  color: inherit;
  transition: all 0.2s ease;
}

.stack-card:hover {
  border-color: var(--accent);
  transform: translateY(-2px);
  box-shadow: var(--shadow-md);
  text-decoration: none;
}

.stack-card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}

.stack-card-title {
  font-size: 1.125rem;
  font-weight: 600;
  margin: 0;
}

.stack-card-version {
  font-size: 0.75rem;
  font-weight: 500;
  padding: 2px 6px;
  background: var(--accent);
  color: var(--bg-primary);
  border-radius: var(--radius-sm);
}

.stack-card-description {
  font-size: 0.875rem;
  color: var(--text-secondary);
  margin: 0 0 16px;
  line-height: 1.5;
}

.stack-card-stats {
  display: flex;
  gap: 24px;
}

.stat {
  display: flex;
  flex-direction: column;
}

.stat-value {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--accent);
}

.stat-label {
  font-size: 0.75rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

/* Filters section */
.filters-section {
  display: flex;
  flex-wrap: wrap;
  gap: 24px;
  padding: 20px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  margin-bottom: 24px;
}

.filter-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.filter-label {
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.filter-buttons {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.filter-btn {
  padding: 6px 12px;
  font-size: 0.8rem;
  font-weight: 500;
  color: var(--text-muted);
  background: transparent;
  border: 2px solid var(--border);
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: all 0.15s ease;
  opacity: 0.5;
}

.filter-btn:hover {
  opacity: 0.8;
}

.filter-btn.active {
  opacity: 1;
  color: white;
  font-weight: 600;
}

/* Status filter buttons - match status badge colors */
.filter-btn[data-value="operational"] {
  border-color: #10b981;
  color: #10b981;
}
.filter-btn[data-value="operational"].active {
  background: #10b981;
  border-color: #10b981;
  color: white;
}

.filter-btn[data-value="implemented"] {
  border-color: #3b82f6;
  color: #3b82f6;
}
.filter-btn[data-value="implemented"].active {
  background: #3b82f6;
  border-color: #3b82f6;
  color: white;
}

.filter-btn[data-value="in-progress"] {
  border-color: #f59e0b;
  color: #f59e0b;
}
.filter-btn[data-value="in-progress"].active {
  background: #f59e0b;
  border-color: #f59e0b;
  color: white;
}

.filter-btn[data-value="planned"] {
  border-color: #9ca3af;
  color: #9ca3af;
}
.filter-btn[data-value="planned"].active {
  background: #9ca3af;
  border-color: #9ca3af;
  color: white;
}

.filter-btn[data-value="deprecated"] {
  border-color: #ef4444;
  color: #ef4444;
}
.filter-btn[data-value="deprecated"].active {
  background: #ef4444;
  border-color: #ef4444;
  color: white;
}

/* Maturity filter buttons - match maturity badge colors */
.filter-btn[data-value="1"] {
  border-color: #ef4444;
  color: #ef4444;
}
.filter-btn[data-value="1"].active {
  background: #ef4444;
  border-color: #ef4444;
  color: white;
}

.filter-btn[data-value="2"] {
  border-color: #f59e0b;
  color: #f59e0b;
}
.filter-btn[data-value="2"].active {
  background: #f59e0b;
  border-color: #f59e0b;
  color: white;
}

.filter-btn[data-value="3"] {
  border-color: #eab308;
  color: #eab308;
}
.filter-btn[data-value="3"].active {
  background: #eab308;
  border-color: #eab308;
  color: white;
}

.filter-btn[data-value="4"] {
  border-color: #22c55e;
  color: #22c55e;
}
.filter-btn[data-value="4"].active {
  background: #22c55e;
  border-color: #22c55e;
  color: white;
}

.filter-btn[data-value="5"] {
  border-color: #3b82f6;
  color: #3b82f6;
}
.filter-btn[data-value="5"].active {
  background: #3b82f6;
  border-color: #3b82f6;
  color: white;
}

/* Stack layers */
.stack-layers {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.layer {
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 20px;
  margin-bottom: 20px;
}

.layer:last-child {
  margin-bottom: 0;
}

.layer--foundational {
  background: linear-gradient(135deg, rgba(245, 158, 11, 0.1) 0%, rgba(245, 158, 11, 0.05) 100%);
  border: 2px dashed #f59e0b;
}

/* Capabilities grid */
.capabilities-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
  gap: 10px;
}

.capability-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 14px 16px;
  background: var(--bg-tertiary);
  border-radius: var(--radius-md);
  text-decoration: none;
  color: inherit;
  text-align: center;
  transition: all 0.2s ease;
  box-shadow: var(--shadow-sm);
  position: relative;
}

.capability-card:hover {
  transform: translateY(-2px);
  box-shadow: var(--shadow-md);
  text-decoration: none;
}

.capability-card.filtered-out {
  opacity: 0.3;
  transform: scale(0.98);
}

/* Metrics count indicator - like Facebook unread badge */
.metrics-indicator {
  position: absolute;
  top: -6px;
  right: -6px;
  min-width: 20px;
  height: 20px;
  padding: 0 6px;
  background: #3b82f6;
  color: white;
  font-size: 11px;
  font-weight: 600;
  line-height: 20px;
  text-align: center;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}

.capability-name {
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.3;
}

.capability-badges {
  display: flex;
  gap: 4px;
}

/* Top navigation */
.top-nav {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 0.875rem;
  padding: 12px 16px;
  margin: 16px 0;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
}

.top-nav-link {
  color: var(--accent);
  font-weight: 500;
}

.top-nav-link:hover {
  text-decoration: underline;
}

.top-nav-sep {
  color: var(--text-muted);
}

.top-nav-current {
  color: var(--text-primary);
  font-weight: 600;
}

/* Breadcrumb */
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 0.875rem;
  color: var(--text-muted);
  margin: 16px 0;
}

.breadcrumb-sep {
  color: var(--border);
}

/* Capability detail */
.capability-detail {
  max-width: 800px;
}

.capability-meta {
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 20px;
  margin-bottom: 24px;
}

.meta-row {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 8px 0;
  border-bottom: 1px solid var(--border);
}

.meta-row:last-child {
  border-bottom: none;
}

.meta-label {
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--text-muted);
  min-width: 100px;
}

.meta-value {
  font-size: 0.875rem;
  color: var(--text-primary);
}

.capability-description,
.capability-dependencies,
.capability-slis {
  margin-bottom: 24px;
}

.capability-description h2,
.capability-dependencies h2,
.capability-slis h2 {
  font-size: 1rem;
  font-weight: 600;
  margin: 0 0 12px;
  color: var(--text-primary);
}

.capability-description p {
  font-size: 0.875rem;
  line-height: 1.6;
  color: var(--text-secondary);
  margin: 0;
}

.dependency-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.dependency-list li {
  padding: 8px 0;
  border-bottom: 1px solid var(--border);
}

.dependency-list li:last-child {
  border-bottom: none;
}

.sli-summary {
  font-size: 0.875rem;
  color: var(--text-secondary);
  margin: 0;
}

/* Fallback header (when site-nav JS not available) */
.fallback-header {
  margin-bottom: 24px;
}

.fallback-header h1 {
  font-size: 1.5rem;
  font-weight: 700;
  margin: 0 0 8px;
  color: var(--text-primary);
}

.fallback-header .version {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 500;
  padding: 2px 8px;
  margin-left: 8px;
  background: var(--accent);
  color: var(--bg-primary);
  border-radius: var(--radius-sm);
}

.fallback-header p {
  font-size: 0.875rem;
  color: var(--text-secondary);
  margin: 0;
}

/* Fallback badges (when site-nav JS not available) */
.status-badge,
.maturity-badge {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 500;
  padding: 2px 8px;
  border-radius: var(--radius-sm);
  text-transform: capitalize;
}

.status-operational { background: #10b981; color: white; }
.status-implemented { background: #3b82f6; color: white; }
.status-in-progress { background: #f59e0b; color: white; }
.status-planned { background: #9ca3af; color: white; }
.status-deprecated { background: #ef4444; color: white; }

.maturity-m1 { background: #ef4444; color: white; }
.maturity-m2 { background: #f59e0b; color: white; }
.maturity-m3 { background: #eab308; color: white; }
.maturity-m4 { background: #22c55e; color: white; }
.maturity-m5 { background: #3b82f6; color: white; }

/* Bullet Chart Styles */
.bullet { font: 12px sans-serif; }
.bullet .marker { stroke: #000; stroke-width: 2px; }
.bullet .tick line { stroke: #666; stroke-width: .5px; }
.bullet .range.s0 { fill: #dcfce7; }
.bullet .range.s1 { fill: #fef3c7; }
.bullet .range.s2 { fill: #fee2e2; }
.bullet .measure.s0 { fill: #3b82f6; }
.bullet .measure.s1 { fill: #60a5fa; }

.bullet-legend {
  display: flex;
  gap: 16px;
  font-size: 11px;
  margin-bottom: 16px;
  color: var(--text-secondary);
}

.bullet-legend-item {
  display: flex;
  align-items: center;
  gap: 4px;
}

.bullet-legend-swatch {
  width: 12px;
  height: 12px;
  border-radius: 2px;
}

.bullet-container {
  padding: 8px 0;
}

.bullet-row {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
  gap: 12px;
}

/* Metrics group collapse animation */
.metrics-group {
  transition: opacity 0.2s ease, margin 0.2s ease;
}

.metrics-group[style*="display: none"] {
  opacity: 0;
  margin: 0;
}

.bullet-label {
  flex: 0 0 auto;
  text-align: left;
  min-width: 180px;
}

.bullet-label-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--text-primary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 250px;
}

.bullet-label-subtitle {
  font-size: 12px;
  color: var(--text-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.bullet-chart {
  flex: 1 1 auto;
  min-width: 200px;
}

/* Page Navigation */
.page-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-bottom: 24px;
  padding: 8px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
}

.page-nav-link {
  padding: 10px 18px;
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--text-secondary);
  text-decoration: none;
  background: transparent;
  border: 1px solid transparent;
  border-radius: var(--radius-md);
  transition: all 0.2s ease;
}

.page-nav-link:hover {
  color: var(--text-primary);
  background: var(--bg-tertiary);
  text-decoration: none;
}

.page-nav-link.active {
  color: var(--bg-primary);
  background: var(--accent);
  border-color: var(--accent);
}

/* Layer Header with count */
.layer-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  margin-bottom: 12px;
  background: var(--bg-tertiary);
  border-radius: var(--radius-md);
}

.layer-title {
  font-size: 0.9rem;
  font-weight: 600;
  color: var(--text-primary);
}

.layer-count {
  font-size: 0.75rem;
  font-weight: 500;
  color: var(--text-muted);
  padding: 3px 8px;
  background: var(--bg-primary);
  border-radius: var(--radius-sm);
}

/* Metrics View Header */
.metrics-view-header {
  padding: 16px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  margin-bottom: 20px;
}

.metrics-view-header .bullet-legend {
  margin-bottom: 0;
}

/* Metrics Groups */
.metrics-group {
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  margin-bottom: 16px;
  overflow: hidden;
}

.metrics-group-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 14px 20px;
  background: var(--bg-tertiary);
  border-bottom: 1px solid var(--border);
}

.metrics-group-title {
  font-size: 1rem;
  font-weight: 600;
  color: var(--text-primary);
}

.metrics-group-count {
  font-size: 0.75rem;
  font-weight: 500;
  color: var(--text-muted);
  padding: 4px 10px;
  background: var(--bg-primary);
  border-radius: var(--radius-sm);
}

.metrics-group .bullet-container {
  padding: 20px;
}

/* SLI Level Badge in bullet rows */
.bullet-label-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 2px;
}

.sli-level-badge {
  font-size: 11px;
  font-weight: 600;
  padding: 2px 6px;
  border-radius: 3px;
  color: white;
}

.sli-level-badge.level-m1 { background: #ef4444; }
.sli-level-badge.level-m2 { background: #f59e0b; }
.sli-level-badge.level-m3 { background: #eab308; }
.sli-level-badge.level-m4 { background: #22c55e; }
.sli-level-badge.level-m5 { background: #3b82f6; }

/* Responsive */
@media (max-width: 640px) {
  .site-container {
    padding: 16px;
  }

  .cards-grid {
    grid-template-columns: 1fr;
  }

  .capabilities-grid {
    grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  }

  .filters-section {
    flex-direction: column;
  }
}
`
