package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/grokify/prism/sitegen"
	"github.com/spf13/cobra"
)

var (
	siteTitle           string
	siteDescription     string
	siteStacks          []string // Can be files or directories
	siteModelsDir       string
	siteStatesDir       string
	siteOutputDir       string
	siteTheme           string
	siteBaseURL         string
	siteSiteNavJS       string
	siteHideGeneratedBy bool
	siteCapStack        string // capability stack for layer views
	siteAggMethod       string // aggregation method (min/avg)
)

var siteCmd = &cobra.Command{
	Use:   "site",
	Short: "Static site generation",
	Long:  `Commands for generating static websites from PRISM data.`,
}

var siteGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a static site from PRISM data",
	Long: `Generates a multi-page static website from capability stacks,
maturity models, and state documents.

The generated site includes:
  - Homepage with cards linking to all capability stacks
  - Stack pages with filterable capability grids
  - Capability detail pages with SLI metrics

STANDARD PRISM DIRECTORY STRUCTURE (recommended):

  {stack-name}/
  ├── stack.json           # Capability stack definition
  ├── model.json           # Maturity model (SLIs, levels, criteria)
  ├── state.json           # Current state (SLI values)
  └── roadmap.json         # OKRs, initiatives (optional)

When using standard structure, all files are auto-discovered:

  prism site generate --stack=./security/ --stack=./reliability/

Or point to a parent directory containing multiple stack directories:

  stacks/
  ├── security/
  │   ├── stack.json
  │   ├── model.json
  │   └── state.json
  └── reliability/
      ├── stack.json
      ├── model.json
      └── state.json

  prism site generate --stack=./stacks/ --output=./dist

LEGACY MODE (separate directories):

For non-standard layouts, use --models and --states directories:

  prism site generate \
    --stack=./stacks/security.json \
    --models=./models/ \
    --states=./states/ \
    --output=./dist

Model/state files are matched by naming convention:
  - {basename}-model.json or {basename}/model.json
  - {basename}-state.json or {basename}/state.json

Examples:
  # Single standard stack directory
  prism site generate --stack=./security/ --output=./dist

  # Multiple standard stack directories
  prism site generate \
    --stack=./security/ \
    --stack=./reliability/ \
    --output=./dist \
    --title="PRISM Dashboard"

  # Parent directory with multiple stacks
  prism site generate \
    --stack=./stacks/ \
    --output=./dist/ \
    --theme=dark

  # Legacy: separate files with models/states directories
  prism site generate \
    --stack=./security-stack.json \
    --models=./models/ \
    --states=./states/ \
    --output=./dist`,
	RunE: runSiteGenerate,
}

func init() {
	siteGenerateCmd.Flags().StringVar(&siteTitle, "title", "PRISM Dashboard", "Site title")
	siteGenerateCmd.Flags().StringVar(&siteDescription, "description", "Capability maturity dashboard", "Site description")
	siteGenerateCmd.Flags().StringSliceVar(&siteStacks, "stack", nil, "Capability stack file(s) or directory (can be repeated)")
	siteGenerateCmd.Flags().StringVar(&siteModelsDir, "models", "", "Directory containing maturity model JSON files")
	siteGenerateCmd.Flags().StringVar(&siteStatesDir, "states", "", "Directory containing state JSON files")
	siteGenerateCmd.Flags().StringVar(&siteOutputDir, "output", "./dist", "Output directory for generated site")
	siteGenerateCmd.Flags().StringVar(&siteTheme, "theme", "dark", "Theme: light or dark")
	siteGenerateCmd.Flags().StringVar(&siteBaseURL, "base-url", "", "Base URL for the site (for absolute links)")
	siteGenerateCmd.Flags().StringVar(&siteSiteNavJS, "site-nav-js", "", "Path to site-nav JavaScript bundle")
	siteGenerateCmd.Flags().BoolVar(&siteHideGeneratedBy, "hide-generated-by", false, "Hide the 'Generated by PRISM' footer message")
	siteGenerateCmd.Flags().StringVar(&siteCapStack, "capstack", "", "Capability stack file for layer-based maturity views")
	siteGenerateCmd.Flags().StringVar(&siteAggMethod, "aggregation", "min", "Aggregation method: 'min' (conservative) or 'avg' (average)")

	if err := siteGenerateCmd.MarkFlagRequired("stack"); err != nil {
		panic(err)
	}

	siteCmd.AddCommand(siteGenerateCmd)
}

func runSiteGenerate(cmd *cobra.Command, args []string) error {
	// Validate aggregation method
	aggMethod := strings.ToLower(siteAggMethod)
	switch aggMethod {
	case "min", "":
		aggMethod = "min"
	case "avg", "average":
		aggMethod = "avg"
	default:
		return fmt.Errorf("invalid aggregation method: %s (use 'min' or 'avg')", siteAggMethod)
	}

	// Validate and convert stack paths to absolute
	var stackPaths []string
	for _, p := range siteStacks {
		absPath, err := filepath.Abs(p)
		if err != nil {
			return fmt.Errorf("invalid stack path %s: %w", p, err)
		}
		if _, err := os.Stat(absPath); os.IsNotExist(err) {
			return fmt.Errorf("stack path does not exist: %s", p)
		}
		stackPaths = append(stackPaths, absPath)
	}

	// Convert other paths to absolute
	var modelsDir, statesDir, capStackPath string
	var err error

	if siteModelsDir != "" {
		modelsDir, err = filepath.Abs(siteModelsDir)
		if err != nil {
			return err
		}
	}
	if siteStatesDir != "" {
		statesDir, err = filepath.Abs(siteStatesDir)
		if err != nil {
			return err
		}
	}
	if siteCapStack != "" {
		capStackPath, err = filepath.Abs(siteCapStack)
		if err != nil {
			return err
		}
		if _, err := os.Stat(capStackPath); os.IsNotExist(err) {
			return fmt.Errorf("capstack path does not exist: %s", siteCapStack)
		}
	}

	outputDir, err := filepath.Abs(siteOutputDir)
	if err != nil {
		return err
	}

	config := sitegen.Config{
		Title:             siteTitle,
		Description:       siteDescription,
		StackPaths:        stackPaths,
		ModelsDir:         modelsDir,
		StatesDir:         statesDir,
		OutputDir:         outputDir,
		Theme:             siteTheme,
		BaseURL:           siteBaseURL,
		SiteNavJS:         siteSiteNavJS,
		HideGeneratedBy:   siteHideGeneratedBy,
		CapStackPath:      capStackPath,
		AggregationMethod: aggMethod,
	}

	gen := sitegen.NewGenerator(config)

	fmt.Fprintf(os.Stderr, "Generating site...\n")
	fmt.Fprintf(os.Stderr, "  Stacks: %v\n", stackPaths)
	if modelsDir != "" {
		fmt.Fprintf(os.Stderr, "  Models: %s\n", modelsDir)
	}
	if statesDir != "" {
		fmt.Fprintf(os.Stderr, "  States: %s\n", statesDir)
	}
	fmt.Fprintf(os.Stderr, "  Output: %s\n", outputDir)

	if err := gen.Generate(); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "\nSite generated successfully!\n")
	fmt.Fprintf(os.Stderr, "Open %s/index.html to view.\n", outputDir)

	return nil
}
